percona/percona-backup-mongodb

Makefile
cli/pbm-agent/main.go
cli/pbm-coordinator/main.go
cli/pbmctl/main.go

1. Add kingpin .Short() flags to common/required flags. Try to match mongodb-tools' short flags so the tool feels natural.
1. Re-order/group coordinator kingpin flags to clean --help output to match changes in agent+pbmctl in #151.
1. Add 'tls_' suffix to TLS-related options to match changes in agent+pbmctl in #151.
1. Update Makefile to cleanup UPX temp files (*.000 and *.upx).
1. Fixed typo in help field.
```
$ ./pbm-agent --help
usage: pbm-agent [<flags>]
Percona Backup for MongoDB agent
Flags:
--help                     Show context-sensitive help (also try --help-long and --help-man).
--version                  Show application version.
-c, --config-file="config.yml"  
Backup agent config file
--generate-sample-config   Generate sample config.yml file with the defaults
-d, …
```

CLI --help/flags cleanup #2

---

cli/pbm-agent/run-agents.sh
cli/pbm-coordinator/main.go
grpc/server/clients.go
grpc/server/server.go
internal/testutils/grpc/daemon.go

Resolves error:
```
Cannot call DBBackupFinished RPC method: rpc error: code = Unknown desc = DBBackupFinished: cannot find a primary in the clients list for replicaset rs0
```
BUT oplogs still are not uploaded.

PBM-157: Refresh client state before backup (and every N x seconds) to fix stale agent states

---

Gopkg.lock
Gopkg.toml

Resolve 'dep' warning:
```
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
✗  golang.org/x/net
However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.
Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.
```

Fix dep warning for x/net package

---

cli/pbm-agent/main.go
cli/pbm-coordinator/main.go
cli/pbmctl/main.go

1. Remove 'snappy' from ServerCompressor 'help' message.
1. Add 'none' to grpcCompressors slice so that compression can be disabled.

Remove 'snappy' from ServerCompressors, add 'none' type 

---

cli/pbm-agent/main.go

Fix broken reconnect logic in pbm-agent. Currently it reconnects in a loop with no delay:
```
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers 
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers 
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers 
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers 
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers 
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers 
ERROR[2019-02-09T16:09:35+01:00] Cannot connect to MongoDB at 127.0.0.1:27017: no reachable servers …
```

Fix reconnect logic in pbm-agent

---

Gopkg.lock
Gopkg.toml
Makefile
docker-compose.yml
grpc/client/client.go
grpc/server/server.go
internal/backup/hotbackup/backup_test.go
internal/backup/hotbackup/restore_test.go
internal/oplog/oplog_apply.go
internal/oplog/oplog_apply_test.go
internal/restore/restore.go
internal/restore/restore_test.go
internal/testutils/db.go
internal/testutils/env.go
setenv.sh
tests/general_test.go
tests/restore_test.go

- Updated mongo tools dependencies to version r4.0.8
- Fixed sandbox to run MongoDB or Percona Server for MongoDB
- Fixed client to support Mongodb 4.0 config servers
- Fixed client to preserve UUIDs when restoring
- Updated modules to handle multi-errors
- Improved tests
- Clean up temp dir and busckets after testing

PBM-184 Updated to work with MongoDB 4.0

---

cli/pbm-agent/main.go
cli/pbm-agent/main_test.go
grpc/client/client.go
internal/testutils/grpc/daemon.go
tests/general_test.go

Also added a new channel to signal the agent's stop to the db watchdog.
Cannot use the context.Done() because the context is being re-initialized upon reconnection.

PBM-248 Enable SSL support for mongo sessions

---

Makefile
cli/pbm-agent/main.go
docker/test/entrypoint-mongod.sh

Fixed: pbm-agent will connect to a secondary from a docker container.
New features:
--dump-config: option to dump the cli options and storage to help debugging
--generate-sample-storage: option to generate a sample storage config option to make it easier to define new storage config

PBM-281 Fix agent's connection to a secondary

---

Makefile

The module github.com/mongodb/mongo-tools-common@v0.0.1-0.20190823135426-6379cde3ec10 seems to not exist anymore:
``` bash
[d@wks percona-backup-mongodb]$ go mod tidy
go: github.com/mongodb/mongo-tools-common@v0.0.1-0.20190823135426-6379cde3ec10: invalid version: unknown revision 6379cde3ec10
```
Recreating go.mod from scratch works, but I am not 100% confident that the new dependencies do not affect the code functionality (more tests would be needed).
Building the binaries using the dependencies' vendored version is an alternative solution that fixed the potential missing versions.

Use vendor tree to build binaries.

---

cmd/pbm/main.go

If the file was malformed (e.g. misformatted) and the improper config was set, there is quite a chance user will notice that in the output.

Show config after it was set from a file

---

cmd/pbm/backup.go
pbm/backup/dst.go
pbm/config.go
pbm/restore/src.go

Hi @dAdAbird,
This pull request replaces https://github.com/percona/percona-backup-mongodb/pull/289.
The new storage config file should look like this:
```yaml
storage:
type: s3
s3:
region: <s3 region>
bucket: <my s3 bucket name>
prefix: <desired folder hierarchy inside bucket> # optional
credentials:
access-key-id: <my s3 access key id>
secret-access-key: <my s3 secret access key>
```
If a prefix is defined, the user will receive the following feedback upon backup creation:
```bash
Starting backup '2019-11-17T16:20:19Z'...
Backup '2019-11-17T16:20:19Z' to remote store 's3://<bucket>/<prefix>' has started
```
I have tested backup, list and restore operations with and without prefix and everything works as expected.

Add s3 storage config prefix

---

pbm/pbm.go

Except for the `replicaSet` which causes an error while reconnecting to the ConfigServer on a sharded cluster

PBM-369 Preserve parameters from user provided URL

---

doc/source/.res/code-block/bash/pbm-list-mongodb-uri.txt
doc/source/.res/code-block/bash/systemd-unit-file.txt
doc/source/architecture.rst
doc/source/authentication.rst
doc/source/config.rst
doc/source/contributing.rst
doc/source/index.rst
doc/source/installation.rst
doc/source/intro.rst
doc/source/running.rst
doc/source/uninstalling.rst

Hi Borys. This PR has a few things in my own v1.1 doc rewrite that I want to fix.
One thing especially to note: I've added a new .res file doc/source/.res/code-block/bash/systemd-unit-file.txt that shows an ini-format file. I just optimistically set the code type to "ini" without knowing if that will render. I apologize in advance if it does not. I guess a plain-text format is the next best thing if there is no "ini" formatter.

Late Dec, early Jan touch-up of v1.1 documentation

---

doc/source/authentication.rst
doc/source/installation.rst

The review of the manual was done when PBM was in version 0.5. Many of the comments are not relevant any longer.

PBM-331: Build instructions - update

---

doc/source/.res/code-block/yaml/example-amazon-s3-storage.yaml
doc/source/.res/code-block/yaml/example-local-file-system-store.yaml
doc/source/.res/code-block/yaml/example-minio-s3-storage.yaml
doc/source/running.rst

I mistakenly left "storage:" out of the config file examples when I wrote the v1.1 documentation.
This patch to the three include files fixes that.

PBM-408: Putting storage key as top-level field in config yaml examples

---

pbm/rsync.go

GCP Cloud Storage S3 supports most actions using Amazon S3 V2 API but
listing objects is only supported using the V1 API.
If you try to resync backups when using GCP Cloud Storage S3 you'll get
the error like the one below:
```
2020/02/19 08:46:43 Got command resyncBcpList
2020/02/19 08:46:43 [INFO] resync_list: started
2020/02/19 08:46:43 [ERROR] resync_list: get backups from S3: get backup list: NotImplemented: A header or query you provided requested a function that is not implemented.
status code: 400, request id: , host id:
```
Using the V1 API will however correctly resync the backups:
```
2020/02/19 10:42:37 Got command resyncBcpList
2020/02/19 10:42:37 [INFO] resync_list: started
2020/02/19 10:42:38 [INFO] resync_list: succeed
```
It may be somewhat controversial to use an older …

Add support for GCP Cloud Storage S3

---

pbm/pbm.go

The sort on "start_ts" was 1 (ascending) rather than -1 (descending). This leads to incorrectly showing the oldest rather than the latest backups when using the --size parameter to "pbm list".

PBM-438 Fix sort-by order in BackupList()

---

cmd/pbm/backup.go
cmd/pbm/restore.go
pbm/restore.go

Fix for PBM-438 changed the listing order so the most recent backups became at the top of the list. This commit restores the listing order returning backup the behaviour when the most recent backups are listed in the bottom.
was
```
$ pbm list
Backup history:
2020-04-03T12:38:26Z
2020-03-17T20:37:39Z
2020-03-17T19:37:40Z
```
become:
```
$ pbm list
Backup history:
2020-03-17T19:37:40Z
2020-03-17T20:37:39Z
2020-04-03T12:38:26Z
```
It also fixes the restore listing.

PBM-438 Fix pbm list layout order

---

cmd/pbm-speed-test/main.go
cmd/pbm/backup.go
cmd/pbm/main.go
e2e-tests/cmd/pbm-test/main.go
e2e-tests/docker/docker-compose.yaml
e2e-tests/functions
e2e-tests/pkg/pbm/mongo_pbm.go
e2e-tests/pkg/pbm/pbm_ctl.go
e2e-tests/pkg/tests/sharded/cluster.go
e2e-tests/pkg/tests/sharded/test_basic.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
e2e-tests/pkg/tests/sharded/test_network_cut.go
e2e-tests/pkg/tests/sharded/test_trx.go
pbm/backup/backup.go
pbm/backup/dst.go
pbm/config.go
pbm/delete.go
pbm/pbm.go
pbm/restore/restore.go
pbm/restore/src.go
pbm/rsync.go
pbm/storage/blackhole/blackhole.go
pbm/storage/fs/fs.go
pbm/storage/s3/s3.go
pbm/storage/storage.go
speedt/speedt.go

`pbm delete-backup 2020-04-20T13:38:55Z` deletes specified backup
`pbm delete-backup --older-than 2020-04-20T13:13:20Z` deletes all backups that was made before specified. The argument is a backup name from `pbm list`. Specified backup is NOT being deleted in that case, only preceding backups. E.g.:
```
$ pbm list
Backup history:
2020-04-20T10:55:42Z
2020-04-20T13:07:34Z
2020-04-20T13:13:20Z
$ pbm delete-backup -f --older-than 2020-04-20T13:13:20Z
Backup history:
2020-04-20T13:13:20Z
```
By default delete-backup asks confirmation:
```
$ pbm delete-backup 2020-04-20T13:45:59Z
Are you shure you want delete backup(s)? [y/N]
```
Confirmation can be disabled by adding the flag `--force` or `-f`
Also, backup can be deleted only if it is NOT running (i.e. state is "done" or "error").
```
$ pbm …
```

PBM-348 Drop backup

---

pbm/backup/backup.go

It's going to look something like that
```
2020/05/06 21:31:12 Backup 2020-05-06T18:31:12Z started on node rs2/localhost:28018
2020-05-06T21:31:14.797+0300	writing admin.system.users to archive on stdout
2020-05-06T21:31:14.799+0300	done dumping admin.system.users (2 documents)
2020-05-06T21:31:14.800+0300	writing admin.system.roles to archive on stdout
2020-05-06T21:31:14.807+0300	done dumping admin.system.roles (1 document)
2020-05-06T21:31:14.807+0300	writing admin.system.version to archive on stdout
2020-05-06T21:31:14.815+0300	done dumping admin.system.version (3 documents)
2020-05-06T21:31:14.816+0300	writing test.testt to archive on stdout
2020-05-06T21:31:14.829+0300	writing test.testt2 to archive on stdout
2020-05-06T21:31:14.829+0300	writing …
```

PBM-429 Log mongodump progress

---

agent/snapshot.go
pbm/backup/backup.go
pbm/pbm.go

If some node is lagging after it received backup command it may "wake up" after the backup, in fact, was already done. But the node will try to make a new one. Which in turn will create a mess.
1. Backup's meta collection now has a unique index by backup name. So trying to create "a new" meta will result in an error and this redundant attempt will fail. But this prevents only the leader node from starting the backup
2. We also should prevent lagging nodes from spoiling a valid backup meta with the errors of a failed attempt. For that, some extra checks have been added to the change meta status procedure.
Fix https://jira.percona.com/browse/PBM-520

PBM-520 fix: backup's meta should be unique

---

Makefile
pbm/backup/backup.go
pbm/pbm.go
version/version.go

It also changes the version definition from the last tag in git to manually assigned

PBM-500 feature: Emit pbm version info to the backup's meta

---

pbm/backup/backup.go

After the backups (snapshot) was sucessfully done on all agents the leader agent changes the status in metadata to done. The issue is that the rest of agents don't wait for the meta to be updated before they finish the job and release their locks. It wasn't an issue before.
But with PITR it may happen that
1. The node release the lock before the status in meta was updated.
2. PITR process on the same RS acquires the lock and start pitr.Catchup() process while the status for the recent backup still hadn't updated.
4. Catchup observes the recent backup as still yet not finished and defines the starting point as the last PITR chunk before the backup.
At least the leader's RS would define the last backup as the starting point (its lock gonna be released only after the meta was updated). …

PBM-535 fix: PITR failed to properly define the starting point

---

pbm/backup/backup.go
pbm/node.go
pbm/pitr/pitr.go
pbm/storage/blackhole/blackhole.go
pbm/storage/fs/fs.go
pbm/storage/s3/s3.go
pbm/storage/storage.go
speedt/speedt.go

MaxUploadParts is 1e4 so with PartSize 10Mb the max allowed file size would be ~ 97.6Gb. Hence if the file size is bigger we're enlarging PartSize so PartSize * MaxUploadParts could fit the file. If calculated PartSize is smaller than the default we leave the default.
If UploadPartSize option was set we use it instead of the default. Even with the UploadPartSize set the calculated PartSize woulbe used if it's bigger.
If backup won't be compressed we're assuming that the dump size could be up to 4x lagrer due to mongo's wieredtiger compression. Otherwise, we assume that it would 
be covered by our compression. But in any case, there is an extra 10% gap while calculating chunk size.

PBM-485 fix: Upload 100gb+ db on aws

---

agent/agent.go
agent/pitr.go
agent/snapshot.go
cmd/pbm-agent/main.go
pbm/backup/backup.go
pbm/log.go
pbm/pbm.go
pbm/restore/restore.go
version/version.go

Timezone across the log unified to the **_local format_** (not UTC) as there is no way to change that option for the mongo-tools (mongodump/mongorestre) logger.
Also, data/time format changed to be consistent across the logs.
For example
was
```
2020/09/18 15:12:55 [INFO] backup/2020-09-18T12:12:38Z: backup started
2020-09-18T15:12:58.0001+0300	writing admin.system.users to archive on stdout
2020-09-18T15:12:58.0001+0300	done dumping admin.system.users (2 documents)
2020-09-18T15:12:58.0001+0300	done dumping config.migrations (0 documents)
2020/09/18 15:12:58 [INFO] backup/2020-09-18T12:12:38Z: mongodump finished, waiting for the oplog
```
now
```
2020-09-23T17:13:11.000+0300 [INFO] backup/2020-09-23T14:12:54Z: backup started
2020-09-23T17:13:14.562+0300	writing admin.system.users to …
```

PBM-551 fix: unify log timezones and date/time format

---

agent/pitr.go
pbm/pitr/pitr.go

After the backup finished and the PITR slicer is resuming its operations it may find out that operation being "stolen" by another node. That's ok. And it shouldn't write "error" in the log on that matter.
https://jira.percona.com/browse/PBM-558

PBM-558 fix: error message when PITR slicing moved to another node

---

agent/agent.go
cmd/pbm/main.go
pbm/lock.go
pbm/log.go
pbm/pbm.go

Running deletes by “pbm” CLI might lead to issues with file permissions (file ower/group) on FS. So delete-backup operations should be executed by agents.
1. Locking
In order to run delete operations agents have to acquire locks (to decide which one is going to do the job). This means that no deletes allowed during:
1. Restores. Which is good since the user won’t able to delete backup from which restore is performing. Now that’s possible.
2. Backups. Which gives nothing since delete op refuses to do anything until the backup is either in “done” or “error” state. So the user can’t shoot in their foot deleting running backup even without locks.
3. PITR. Which again brings no value since delete op has the protection against deleting latest snapshot and derived from it pirt slices if PITR is …

PBM-547 fix: move delete ops to agent

---

agent/agent.go
cmd/pbm/main.go
pbm/lock.go

The delete op could be finished fast enough so the other node in the RS may acquire a lock for the same operation.
It may lead to errors in logs (and in CLI) "Error: deleting: unable to delete backup in ' ' state".
Meaning the tries to delete the backup that is already has been deleted.
To prevent this races the node that finished delete has to wait some time so the lock should be held at least for 5 sec. Hence other nodes could observe this lock and abort.

PBM-547 fix locking

---

agent/snapshot.go
cmd/pbm/backup.go
pbm/backup/oplog.go
pbm/config.go

During the oplog slicing, before processing the first oplog record we check if oplog has sufficient range,
i.e. if there are no gaps between the ts of the last backup or slice and
the first record of the current slice. Whereas the request is >= last_saved_ts
and no monotonic increment for oplog records we can't tell
if the returned oldest record is the first since last_saved_ts or
there were other records that are now removed because of oplog collection capacity.
So after we retrieved the first record of the current slice we check if there is
at least one preceding record (basically if there is still record(s) from the previous set).
If so, we can be sure we have a contiguous history with respect to the last_saved_slice.
There's a chance of false-negative though.
We should do this check …

PBM-537 feature: check oplog sufficient range

---

e2e-tests/cmd/pbm-test/main.go
pbm/config.go
pbm/restore/restore.go

Added config options
```
restore:
batchSize: 500
numInsertionWorkers: 10
```
Tests on  Mac mini:
- 3.2 GHz 6-Core Intel Core i7
- 64 GB 2667 MHz DDR4
Made for 3Gb and 20Gb datasets.
Datasets consists of ~3e6 and ~2e7 ~1Mb documents.
On both datasets memory consumption was similar.
Restore time for 3Gb dataset:
```
opt/opt       mem         restore time
100/2        275Mb            13'
100/10       269Mb            3'30"
200/10       302Mb            2"
500/10       376Mb            1'40"
2000/20      1.2Gb            1'30"
```
*`opt/opt` - `batchSize/numInsertionWorkers`

PBM-559: restore: decrease batching defaults & expose it to the config

---

pbm/pitr.go
pbm/pitr_test.go

Merging of the PITR timelines from replicates relies on the assumption that RSs are making progress and stops altogether. And if some node fails and then resumes it'll catchup. I.e. there is no gap in timelines possible. But that is the false assumption.
In fact, we can have a station when one more RS stopped slicing while another node(s) making progress. And then after the backup, all nodes resume slicing starting from the backup's end_time leaving the gap in timelines on the RS that had been failed.
This commit changes the algorithm from comparing only timelines with the same index to grinding thru all timelines on other replica sets searching for overlapping ones.

PBM-562 fit: PITR timeline merging

---

pbm/storage/s3/s3.go

Since s3.uploadPartSize is automatically adjusted it could be
useful to see what the value happened to be at the end of the day
Log entry looks like
```
2020-10-07T19:32:28.543+0300 [INFO] s3.uploadPartSize is set to 10485760 (~10Mb)
```
https://jira.percona.com/browse/PBM-568

PBM-568 feature: print s3.uploadPartSize to log

---

pbm/config.go

Type of serverSideEncryption is a pointer to the struct so during the type checking it needs to be taken an underneath type it points to.

PBM-567 fix: set sse options using CLI

---

e2e-tests/pkg/pbm/mongo_pbm.go
e2e-tests/pkg/tests/sharded/test_backup_cancellation.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
pbm/lock.go

Namely changes in the delete procedure because now it has a different locking flow.
https://jira.percona.com/browse/PBM-563

PBM-563: update tests to reflect latest changes

---

agent/agent.go
version/version.go

CLI:
```
$ pbm version
Version:   1.3.2
Platform:  darwin/amd64
GitCommit: 184ef918a2535e90b612cfc325b7c29deedffeb5
GitBranch: main
BuildTime: 2020-10-12_17:01_UTC
GoVersion: go1.14.5
```
Logs
```
2020-10-12T20:03:16.000+0300 [INFO] pbm-agent:
Version:   1.3.2
Platform:  darwin/amd64
GitCommit: 184ef918a2535e90b612cfc325b7c29deedffeb5
GitBranch: main
BuildTime: 2020-10-12_17:01_UTC
GoVersion: go1.14.5
2020-10-12T20:03:16.000+0300 [INFO] starting PITR routine
2020-10-12T20:03:16.000+0300 [INFO] node: rs1/localhost:37019
...
```

Fix version info layout for CLI

---

pbm/backup/backup.go

Currently PBM correctly chooses a secondary to perform a backup on, but instead of dumping from that secondary, pbm-agent connects to the primary and dumps from there. See more details about the setup I'm working with here: https://forums.percona.com/discussion/56353/pbm-agent-on-secondary-dumps-from-primary/p1?new=1
I'm not familiar enough with the code base to say if this might have some unwanted effects, but I did verify that it works correctly with one of our replica sets.

Use direct connection for MongoDump

---

agent/agent.go
cmd/pbm-agent/main.go
cmd/pbm-speed-test/main.go
pbm/backup/backup.go
pbm/node.go

PBM currently dumps a maximum of `runtime.NumCPU()/2` collections concurrently. In our tests, depending on the used compression algorithm, this leads to either saturating the uplink of the backup nodes or very high CPU loads. We have some use cases where applications read from secondaries and we'd prefer to sacrifice some backup speed in order not to compromise those use cases.
This PR introduces a new optional pbm-agent environment variable, `PBM_DUMP_PARALLEL_COLLECTIONS`, for controlling the parallelism. It's not perfect as it doesn't in any way guarantee fairness of resource/bandwidth use, but at least it allows leaving more CPU cores free for other tasks and has an effect on bandwidth usage.
I figured an environment variable would make sense as opposed to using `pbm config` as it's …

Make it possible to configure number of parallel collections to dump

---

agent/snapshot.go

Fixing the two occurrences of the "node _in_ not suitable for restore" log messages to fix the typo, and to make it so we can distinguish one from the other.

PBM-583 Log message improvements

---

doc/source/.res/code-block/bash/#pbm-backup-mongodb-uri.txt#
doc/source/.res/code-block/mongo/db-createuser.txt
doc/source/architecture.rst
doc/source/config.rst
doc/source/configuration-options.rst
doc/source/index.rst
doc/source/installation.rst
doc/source/point-in-time-recovery.rst
doc/source/running.rst
doc/source/storage-configuration.rst

Added a dedicated page with config file options
Added reference to this page from related pages in the docs: config, running
Left only config file management info in config page
Exposed remote storage configuration to a separate page
Fixed code-block language for create user command
Reworked TOC to clearly describe doc sections

PBM-570 A config file options page

---

cmd/pbm/logs.go
cmd/pbm/main.go
pbm/restore/restore.go
pbm/storage/s3/s3.go

Currently when PBM downloads and parses the backup file during restore it has to abort if reading or connection error happens. Since file (object) being downloaded and parsed as a whole, retrying won't help much if an error happened after lest's say 500Gb already had been parsed. "Retrying" in such case would mean do it again from the beginning.
This PR addresses issue by downloading S3 objects in chunks using HTTP Range header https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35.  That makes retries possible if an error happened.
Along with the retries, PBM would recreate session with the S3 should conniption being dropped.
https://jira.percona.com/browse/PBM-555

PBM-555 Retry and reconnect on errors while downloading from S3

---

agent/pitr.go
agent/snapshot.go
pbm/backup/backup.go
pbm/node.go
pbm/pitr/pitr.go
pbm/restore/restore.go

Restore should remove tmp user and role collections otherwise
it would be a conflicting namespaces error during restore
This commit addresses issue by
1. Ensuring that restore would try to drop tmp collections even on error.
Which didn't happened before. The drop was run only on success.
2. Backup would ensure there ate no tmp collections and try to drop it otherwise.
There is no way to exclude some collections on mongodump stage
while it accepts "exclude..." option only if sole db specified (¯\_(ツ)_/¯)
So we're trying to clean up on primary node when it gets bcp command
but because there is no guarantee
that primary node reaches that code before some of the secondaries starts backup
we have to double-check in backup.run() before mongodump and fail on the dirty state. …

PBM-460: Prevent conflicting namespace during the restore

---

pbm/restore/restore.go

When restoring a backup to a cluster consisting of different nodes than the ones the backup was made from, the shard configuration is overwritten. I don't think it makes sense to restore the shard configuration in any conditions because in any case, before restoring a sharded cluster, you need to have a functional cluster set up to begin with.
I almost had a heart attack the first time I noticed that `sh.status()` on my test cluster claimed to be talking to production shards.

Ignore shard configuration from backup

---

pbm/storage/s3/s3.go

It allows not to depend on system keepalive settings and retry earlier if connection stalls.
https://jira.percona.com/browse/PBM-586

PBM-586 feature: add a request timeout to the restore S3 downloader

---

pbm/storage/s3/s3.go

Just a chore. If mongorestore had exited and closed pipe before the download is finished it means that some error happened on that side. So there is no reason in retrying download and spamming log with failed attempts.

PBM-555 don't retry download after mongorestore errors

---

agent/agent.go
agent/snapshot.go
pbm/lock.go

OPID would protect from running the same op twice by different nodes.
Moreover, waiting may trigger bug in k8s operator.  If the database is relatively small -  backups went really fast. Let’s say in 10sec backup being marked as successfully done. But because of timeouts needed for some internal sync pbm-agent would hold the lock for at least 34sec. So we have a situation when operator observes “backup done” and send the next backup command to the PBM. But since some agents still are holding locks this operation either being discarded by PBM straight ahead (because of timing some of the replset may actually start a backup and then “fail” it because “couldn’t get a response from all shards”).
Anyway, the issue is that for small and fast backup operator might think that backup is done (and …

No need to wait and hold a lock for fast ops

---

agent/agent.go
agent/pitr.go
agent/snapshot.go
pbm/lock.go

To progress further with any op agent has to not only acquire a lock but also
log the op by its unique ID. If the log phase has failed agent wasn't removing
lock acquired on the 1st phase.
This commit fixes that bug. Plus rearranges a bit lock-related logging.

Fix: release lock if 2nd phase failed

---

pbm/backup/backup.go
pbm/pitr/pitr.go
pbm/rsync.go

Any upload on storage would create the target file first and then will
stream data into it (data could be lager than the available RAM). And if
something went wrong while reading data we may end up with an already created
empty or inconsistent file. PITR chunks have no metadata along with it to
indicate any failed state. Although the failed PITR range won't be saved in
internal db as the available for restore. It would get in there after the storage
resync. So on any upload errors during the PITR slicing, we have to ensure no
leftovers on storage. And also skip empty PITR chunks during resync.
https://jira.percona.com/browse/PBM-602

PBM-602 fix: discard failed PITR chunks

---

agent/pitr.go
cmd/pbm/backup.go
cmd/pbm/status.go
pbm/log/log.go
pbm/pbm.go
pbm/pitr/pitr.go

Added an extra wait penalty to the next agent's loop iteration
should slicer return with an error.
Also, fixed PITR error messaging in pbm status.
If one agent failed with error the other will catch up. Epoch won't
change but and despite successful slicing by another node pbm status
would display error of failed node. So have to check for no
subsequent success before firing an error.
And remove pitr errors from `pbm list` output

PBM-597 fix: Properly handle mongo fail while PITR slicing

---

cmd/pbm/main.go

```
$ pbm logs --help
usage: pbm logs [<flags>]
PBM logs
Flags:
--help                     Show context-sensitive help (also try --help-long and --help-man).
--mongodb-uri=MONGODB-URI  MongoDB connection string (Default = PBM_MONGODB_URI environment variable)
-t, --tail=20                  Show last N entries, 20 entries are shown by default, 0 for all logs
-o, --out=text                 Output format <text>/<json>
-n, --node=NODE                Target node in format replset[/host:posrt]
-s, --severity=I               Severity level D, I, W, E or F, low to high. Choosing one includes higher levels too.
-e, --event=EVENT              Event in format backup[/2020-10-06T11:45:14Z]. Events: backup, restore, cancelBackup, resyncBcpList, pitr, pitrestore,
delete
-i, --opid=OPID …
```

PBM-606: Improve help description

---

agent/pitr.go

Fixed penalty to the failed node so healthy nodes would have priority on next try.
https://jira.percona.com/browse/PBM-613

PBM-613 fix: PITR error doesn't disappear even after PITR slicer switches to another node

---

cmd/pbm/status.go
pbm/pitr.go
pbm/rsync.go
pbm/storage/blackhole/blackhole.go
pbm/storage/fs/fs.go
pbm/storage/s3/s3.go
pbm/storage/storage.go

`pbm status` used to check the size on the storage for each PITR chunk separately.  So every new chunk made status rendering slower and slower.
This commit introduces chunks cache which is made for each status command so there is one request to the storage instead of many.
https://jira.percona.com/browse/PBM-619

PBM-619: oprimize status resposnse time

---

cmd/pbm/main.go
cmd/pbm/status.go
pbm/rsync.go

Now storage resync checks the availability of all files from snapshot metadata.
And skips the snapshot if something is missing.
Also `pbm list` won't show any list while resync is running. Showing message instead.
https://jira.percona.com/browse/PBM-618

PBM-618 fix: don't resync incomplete snapshots

---

pbm/backup/backup.go
pbm/restore/restore.go

The bug was with the statuses confirmation by secondary agents.
When cluster error  emitted it was returning `nil` instead of generating error.
The same bug was in backups.
https://jira.percona.com/browse/PBM-478

PBM-478 fix: don't restore incomplete backups

---

cmd/pbm/status.go

If the backup is incomplete (error reading bcp files) during the pbm status
command backup marked with "ERROR". It doesn't change any metadata neither
on storage nor at db. Anyway, such backup would be discarded on restore
attempt. As well as during the next storage resync.
Example of output:
```
...
Backups:
========
S3 MinIO http://127.0.0.1:9000/bkt/pbm
Snapshots:
2021-01-20T17:09:46Z 3.28GB [complete: 2021-01-20T17:10:33]
2021-01-13T16:10:20Z 3.28GB [complete: 2021-01-13T16:13:00]
2021-01-13T15:50:54Z 0.00B [ERROR: get file 2021-01-13T15:50:54Z_config.dump.s2: no such file] [2021-01-13T15:53:40]
```
https://jira.percona.com/browse/PBM-621

PBM-621: properly handle incomple bcps in status

---

agent/pitr.go
agent/snapshot.go
cmd/pbm/backup.go
cmd/pbm/backup_test.go
cmd/pbm/main.go
cmd/pbm/status.go
pbm/backup/backup.go
pbm/pbm.go
pbm/restore/restore.go

This commit changes the restore behaviour regarding backup - target cluster match
Now match means that each replset in the backup has respective replset on the target cluster. It's ok if the
cluster has more shards than there are currently in backup.
Also during `pbm list` and `pbm status` we compare each backup with the
current cluster and if backup's data doesn't match cluster backup's meta
would be changed to pbm.StatusError with respective error text emitted. It doesn't change meta on
storage nor in DB (backup is ok, it just doesn't cluster), it is just "in-flight" changes
in given `bcps`.
https://jira.percona.com/browse/PBM-615

PBM-615: check if backups match the cluster

---

cmd/pbm/backup.go
cmd/pbm/backup_test.go
cmd/pbm/status.go
pbm/restore/restore.go

In the case of sharded cluster backup has to have data for the current
config server or for the sole RS in case of non-sharded rs.
This commit makes `pbm list` and `pbm status` report such condition.
As well as improves error reporting during the restore.
https://jira.percona.com/browse/PBM-629

PBM-629: fail if no config server in backup

---

docker/Dockerfile

While building docker image for PBM step "make install" fails with the following error due to the absence of "libkrb5-dev" package:
```Step 4/13 : RUN make install
---> Running in 1c4f7765ae21
GO111MODULE=on GOOS=linux go install -ldflags="-X github.com/percona/percona-backup-mongodb/version.gitCommit=e9d4b1b047209a82076a8a17b4b561cf2405ecd8 -X github.com/percona/percona-backup-mongodb/version.gitBranch=release-1.4.1 -X github.com/percona/percona-backup-mongodb/version.buildTime=2021-01-28_16:14_UTC -X github.com/percona/percona-backup-mongodb/version.version=" -mod=vendor -tags gssapi ./cmd/pbm
In file included from vendor/go.mongodb.org/mongo-driver/x/mongo/driver/auth/internal/gssapi/gss.go:17:
./gss_wrapper.h:8:10: fatal error: gssapi/gssapi.h: No such file or directory
#include …
```

PBM-625 Add build dependency to docker container to build pbm tools

---

cmd/pbm/backup.go
cmd/pbm/restore.go
e2e-tests/cmd/pbm-test/main.go
e2e-tests/docker/pbm-agent/Dockerfile
e2e-tests/pkg/pbm/docker.go
e2e-tests/pkg/pbm/mongo_pbm.go
e2e-tests/pkg/tests/sharded/cluster.go
e2e-tests/pkg/tests/sharded/test_leader_lag.go
pbm/backup/backup.go
pbm/node.go
pbm/pbm.go
pbm/restore/restore.go

If the leader started with some delay in a sharded cluster other agents
would check metadata during "status waiting" and get `0` heartbeat ts
since meta wasn't set yet. So we should wait for meta if it isn't set.
https://jira.percona.com/browse/PBM-635

PBM-635: wait for leader's metadata

---

agent/agent.go

If `.pbm.init` didn't exists and PBM successfully creates it still falls
into the condition of the next error check. And returns
`storage check failed with: no such file`. On the next run, everything gonna be ok but still annoying error in logs...
This commit fixes it.

Fix storage check

---

doc/source/initial-setup.rst
doc/source/installation.rst

Arbiter mongod nodes do not need a pbm-agent installed.

Exclude arbiter nodes when installing pbm-agent

---

cmd/pbm/status.go
pbm/pbm.go

For the single replica set of config server in the sharded cluster, we should retrieve replSetGetStatus in order to get a node list with priority=0 and hidden nodes.
https://jira.percona.com/browse/PBM-642

PBM-642 fix: show priority=0 & hidden nodes in status

---

pbm/restore/restore.go

Since the newly discovered issue with restoring of system.users breaks operator testes

PBM-636: temporarily disable PreserveUUID

---

cmd/pbm/status.go
pbm/pitr.go

PBM status reflecting PITR state should also check locks because there is a lag
between config option and agents' state.
Now `pbm status` in text output shows PITR "ON" if either
config.pitr.enabled=on or there is PITR lock(s). JSON output contains
both options so API users could decide on their own.
JSON:
```
"PITR incremental backup": {
"conf": true,
"run": false,
"error": "2021-04-09T22:32:35.000+0300 E [config/localhost:37028] [pitr] init: defining starting point for the backup: no backup found after the restored 2021-04-06T17:09:48Z, a new backup is required to resume PITR"
}
```
*error is omitted if empty
https://jira.percona.com/browse/PBM-662

PBM-662: PITR status, check if running, not just conf

---

pbm/backup/backup.go
pbm/pbm.go

Although we do synchronise oplog last write across agents in the sharded
cluster, the first write captured oplog is differ across the cluster. Hence
the backup start isn't synchronised. There is no way to start snapshot
(mongodump) at the same cluster time across the nodes. But we can do
that for oplog capturing.
This commit makes oplog start time (cluster time) to be the same across
all nodes. So oplog coverage now is consistent across the cluster not
only for the last write but for the first write as well.
https://jira.percona.com/browse/PBM-490

PBM-490: sync backup start time

---

pbm/backup/backup.go
pbm/node.go

Tmp users and roles collection didn't get into the backup since they were
dropped before due to `defer` evaluation. Hence users other than PBM's
one weren't restoring. The other thing is that DropTMPcoll wasn't dropping
anything (due to a connection bug) on topologies other than single-node
replica sets. So it wasn't an issue on replicasets and sharded clusters.

Fix user and roles collections restore

---

pbm/backup/backup.go
pbm/backup/oplog.go
pbm/node.go
pbm/restore/restore.go

1. We have to be sure that tmp users and roles collections are replicated to the backup node before taking a snapshot.
2. Tmp collection's writes might be captured by the oplog and replayed later during the restore. So we keep tmp collections until restore finish in order not to have `NamespaceNotFound` errors during the replay.

PBM-636: align user/roles tmp collections with the backup/restore

---

pbm/backup/backup.go
pbm/backup/oplog.go
pbm/node.go

We were writing to the primary but reading last_write of the majority.
So time_to_wait usually were some previous write because the needed one wasn't replicated yet to the majority.
Last_write to wait for should be taken not from the majority but from the node we are writing tmp users to.

 PBM-636: fix waiting time for tmp users

---

Makefile
agent/pitr.go
agent/snapshot.go
e2e-tests/pkg/pbm/pbm_ctl.go
pbm/config.go
pbm/pitr/pitr.go

Set in minutes via config option `pitr.oplogSpanMin`. Option is float so fractures of minutes could be set. E.g. `0.5` is 30 sec.
PITR routine every 15 seconds along with `pitr.enabled` would be check `pitr.oplogSpanMin`.
And if the agent runs slicer and span duration has changed, the slicer would be updated with the new value. If the new value is smaller, the slicer also would be woken up to immediately make a slice and reset the timer.
If the new value is bigger, then the slicer won't be woken up (it will apply a new value only after the current span finishes).

PBM-543 feature: Configurable duration PITR slices' span

---

pbm/restore/oplog.go
pbm/storage/s3/s3.go

This commit makes the restore process fail with an error should the error happened during S3 retry read. Previously it was only logged but restore was marked as successful.
https://jira.percona.com/browse/PBM-683

PBM-683 fix: handle retryReader errors during the restore

---

agent/pitr.go
cmd/pbm/main.go

`cancelBackup` label was removed from logs `--help` as there are no log actions happens for this even. When the backup is cancelled event related to the particular backup (in logs too).
https://jira.percona.com/browse/PBM-640

PBM-640: fix logs labels

---

agent/agent.go

Though if storage was failed, check it along with other subsystems (every 5 sec) until it's become ok

PBM-647: status check storage once in a minute

---

cmd/pbm-agent/args.go
cmd/pbm-agent/main.go

When we extract creds from the argument the text became shorter while the mem size remains the same so we have to pad this difference with zeroes.
This leads to a bit strange output if shortened flag followed by any other flag - quite a few spaces between flags.
https://jira.percona.com/browse/PBM-403

PBM-403: hide user credential from ps output

---

agent/agent.go
cli/cli.go
cli/delete.go
e2e-tests/pkg/pbm/pbm_ctl.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
pbm/delete.go
pbm/pbm.go
pbm/pitr.go

Added command `pbm delete-pitr`. With two flags:
- ` -a, --all` - delete all chunks
- `--older-than`
If `--older-than` set, it will be rounded down to the last write of the closest preceding backup in order not to make gaps. So usually it gonna leave some extra chunks. E.g. if `older-than = 13` and the last write of the closest preceding backup is `10` it will leave `11` and `12` chunks as well since `13` won't be restorable without `11` and `12` (contiguous timeline from the backup).
https://jira.percona.com/browse/PBM-652

PBM-652: delete PITR chunks

---

cli/cli.go
version/version.go

This commit aligns `pbm version` output formatting options with the rest of the CLI output.
That means instead of `--format` flag `pbm version` now uses `-o`/`--out` flag.
This commit also adds shortened versions to the `--short` and `--commit` flags:
```
-s, --short                    Show only version info
-c, --commit                   Show only git commit info
```

PBM-632: pbm version: use `-o` flag to set output format

---

cli/list.go
cli/status.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
pbm/pitr.go

In fact, this second is overlaps with the backup's complete time. To restore to this time user should restore the snapshot instead of PITR.
https://jira.percona.com/browse/PBM-686

PBM-686: skip a first second displaying PITR range

---

pbm/restore/restore.go

Check that the last chunk's end-time is not smaller than the target one.
Hence we have oplog events up until the targeted time.

PBM-701 fix: don't restore if PITR time doesn't exist

---

pbm/backup/backup.go
pbm/restore/restore.go
pbm/storage/s3/s3.go

Defers in a couple of methods were using err variable of the parent func.
And were overwriting the returned errors with nil.
https://jira.percona.com/browse/PBM-709

PBM-709 fix: don't overwrite error in defer

---

e2e-tests/docker/docker-compose-rs.yaml
e2e-tests/docker/docker-compose-single.yaml
e2e-tests/docker/docker-compose.yaml
e2e-tests/docker/mongodb-rs/Dockerfile
e2e-tests/functions

It was unable to run tests with UID!=1001 due to permissions on keyFile.
Also there was issues with volume /opt/backup which mounts to docker/backup - pbm creates files with 664 permissions belongs to nobody:nogroup - so directory cannot be deleted locally without using sudo
Here are some fixes

fix tests for UID!=1001

---

e2e-tests/functions
e2e-tests/pkg/tests/sharded/test_timeseries.go

Otherwise, further tests checking db hashes will fail since ts data always restores with the new UUIDs.

Test: cleanup TS collections

---

pbm/log/log.go

The `t` field is gone (it was always empty). Instead, there is a `ts` field containing Unix timestamp of the event

PBM-712 fix: time output in JSON formatted logs

---

agent/agent.go
agent/pitr.go
agent/snapshot.go
cli/backup.go
cli/cli.go
cli/status.go
pbm/backup/backup.go
pbm/log/log.go
pbm/rsync.go

If a backup has no progress hence status is neither `done` nor `error` and
there are no `hb` updates for a while (StaleFrameSec) it should be
PBM-714 fix: properly show backup status in case of no progress
If a backup has no progress hence status is neither `done` nor `error` and
there are no `hb` updates for a while (StaleFrameSec) it should be
properly marked in `pbm status`. Before this commit for ex. backup that had no
election progress, stuck in `starting` with empty replsets was marked as
"Backup has no data for the config server or sole replicaset" by
`bcpsMatchCluster`. Moreover only `done` backup should be processed by
`bcpsMatchCluster`.
Also, added more debug logging.

PBM-714 fix: properly show backup status in case of no progress

---

cli/list.go
cli/status.go
pbm/delete.go
pbm/pbm.go
pbm/pitr/pitr.go
pbm/restore/restore.go

pbm.GetLastBackup() changed to be consistent with other methods and more error-resilient. Now it returns `pbm.ErrNotFound` not just nil result.
Also added debug logging to the command.
https://jira.percona.com/browse/PBM-722

PBM-722 fix: delete-pitr crash if nothing to delete (no backup)

---

cli/cli.go
cli/oplog.go
cli/restore.go

- Added "wait" to the PITR restore and Oplog relay.
- Check for the operation heartbeats during the wait. That will prevent indefinite wait if agents are gone. All nodes in non-sharded env - is the only agent that runs a restore.

PBM-808, PBM-807: CLI - waiting for the logical restore operations

---

cli/status.go

Before:
```
Backups:
========
S3 us-east-1 s3://http://minio:9000/bcp/pbme2etest
Snapshots:
2022-04-13T07:50:30Z 0.00B [ERROR: Backup stuck at `canceled` stage, last beat ts: 1649836246] [2022-04-13T07:50:48]
```
Now:
```
Backups:
========
S3 us-east-1 s3://http://minio:9000/bcp/pbme2etest
Snapshots:
2022-04-13T07:50:30Z 0.00B [!cancelled: 2022-04-13T07:50:48]
```

Fix cancelled backups displaying in pbm status

---

e2e-tests/cmd/pbm-test/run.go
e2e-tests/cmd/pbm-test/run_physical.go
e2e-tests/pkg/tests/sharded/test_bounds_check.go
e2e-tests/pkg/tests/sharded/test_clock_skew.go
e2e-tests/pkg/tests/sharded/test_trx.go
e2e-tests/pkg/tests/sharded/trx.go
e2e-tests/pkg/tests/sharded/trx_phys.go
pbm/restore/physical.go

Unlike with the logical backups, the LastWrite of physical once
"happening" in seconds after the backup start. So, in tests, we should
wait before committing the first transaction.

Fix physical backup tests

---

pbm/bsontypes.go
pbm/node.go
pbm/pbm.go

Check for `db.adminCommand({ getCmdLineOpts: 1}).parsed.sharding.clusterRole` if `ConfigServerState` is anavaliable.
Fixes https://jira.percona.com/browse/PBM-902

PBM-902: fix sharded cluster detection on mongo 6.0

---

pbm/restore/oplog.go

If the creation of a timeseries collection was captured by oplog, it will cause mongod failure during (sometimes after) the restore. 
```
{"t":{"$date":"2022-08-10T14:59:23.606+00:00"},"s":"F",  "c":"ASSERT",   "id":23081,   "ctx":"conn130","msg":"Invariant failure","attr":{"expr":"isTimeseriesBucketsCollection()","msg":"test.tmpAvOB6.create","file":"src/mongo/db/namespace_string.cpp","line":404}}{"t":{"$date":"2022-08-10T14:59:23.606+00:00"},"s":"F",  "c":"ASSERT",   "id":23082,   "ctx":"conn130","msg":"\n\n***aborting after invariant() failure\n\n"}{"t":{"$date":"2022-08-10T14:59:23.606+00:00"},"s":"F",  "c":"CONTROL",  "id":4757800, "ctx":"conn130","msg":"Writing fatal message","attr":{"message":"Got signal: 6 (Aborted).\n"}} 
```
`tmp%%%%%.create` is created by mongo during applyOps …

PBM-929: recreate UUID for ts collections

---

pbm/restore/physical.go

Since heartbeats will be retried anyway, the failed one should generate
a warning instead of an error in logs.

Physical restore: failed hb is not an error

---

pbm/storage/fs/fs.go

During restore we chmod datadir files with the original perms
(as it was during the backup). So it doesn't matter what file perms are
on storage.
https://jira.percona.com/browse/PBM-943

PBM-943: relax permissions for the FS storage

---

cli/backup.go

If there were any security (data-at-rest enc) options ob the backup node, these will be displayed the describe-backup output

PBM-896: show security opts in descibe-backup

---

cli/restore.go

For physical restore any of the `done` or `partlyDone` statuses is a success.

PBM-946, cli: phys restore wait for partlyDone

---

cli/backup.go
cli/status.go
pbm/backup/physical.go
version/version.go

- Legacy (pre 2.0) physical backups should be considered during size calculation.
- Storage size instead of db file size should be used for physical backup size.
- Bump version.

PBM-946: fix phys backups size in status

---

README.md
pbm/config.go
pbm/storage/s3/s3.go

I have completed a partial test of this -- I am able to initialize pbm, list status etc, start a backup. I'm still running that backup so we'll see how it does.
I can confirm that the files written to the S3 repository are encrypted with SSE-C, however.
Generate a SSE-C AES256 key with:
```bash
openssl rand -base64 32
```
Example config file for Backblaze B2:
```yaml
storage:
type: s3
s3:
region: us-west-002
endpointUrl: https://s3.us-west-002.backblazeb2.com
bucket: pbm-test-bucket-name
prefix: data/pbm/backup
credentials:
access-key-id: <redacted>
secret-access-key: <redacted>
serverSideEncryption:
sseCustomerAlgorithm: AES256
sseCustomerKey: "eBYL81+sAigzkanckAeKQ0kitmVAPwN2DfbItdeMlR8="
```
I'll finish my tests but I wanted to get this pushed up for other eyes to look and see if I've …

[PBM-922]: Add support for SSE-C server-side encryption for S3 endpoints

---

cli/cli.go
pbm/log/log.go

Added flag:
usage: pbm logs [<flags>]
PBM logs
Flags:
...
--timezone=TIMEZONE        Timezone of log output. `Local`, `UTC` or a location name corresponding to a file in the IANA Time Zone database, such as `America/New_York`
https://jira.percona.com/browse/PBM-733

PBM-733: add timezone option to pbm logs output

---

Makefile
cmd/pbm-agent-entrypoint/main.go
docker/Dockerfile.k8s

Add an entry point app that starts pbm-agent in k8s. In case env
`PBM_AGENT_SIDECAR` is set to true, it will restart the agent should it
exits (despite with an error or not) after the `PBM_AGENT_SIDECAR_SLEEP`
timeout in sec (default 1)
https://jira.percona.com/browse/PBM-941

PBM-941: add sidecar mode for pbm-agent

---

pbm/pitr/pitr.go
version/version.go

Check for the oplog sufficiency at the beginning of the streaming. And
report `start_ok` only after that check. So ErrInsuffRange from the
previous run won't be rewritten with `start_ok`.
Also, users will see errors immediately (almost) without the misleading
pause due to the timer.

PBM-858: status, always show err for insufficient oplog range

---

pbm/bsontypes.go

When bson value is "omitempty" it won't passi to the mongo and mongo writes default. As the default for float64 is 0, it will be omited by driver (omitempty) and mongo will write its default for an option. And default for `priority` is 1. So when it was 0 it became 1 after the PBM write.
This commit fixes it.
https://jira.percona.com/browse/PBM-978

PBM-978: fix phys restore of hidden nodes

---

agent/snapshot.go
cli/backup.go
cli/cli.go
cli/restore.go
cli/status.go
pbm/backup/backup.go
pbm/backup/physical.go
pbm/pbm.go
pbm/restore.go
pbm/restore/physical.go
pbm/rsync.go

Based on [$backupCursor](https://www.percona.com/blog/2021/06/07/experimental-feature-backupcursorextend-in-percona-server-for-mongodb/) and [WT block incremental backups](https://source.wiredtiger.com/develop/backup.html#backup_incremental-block) [[2](https://github.com/mongodb/mongo/blob/de4669ee3ee4d5952b3aa79c620e38027616a7ef/src/mongo/db/catalog/README.md#file-system-backups)] features
First of all, the user would need to make a full incremental backup (a base). The node will start keeping an incremental backup history. And when a subsequent incremental buck will be requested, the system will be able to calculate and provide the difference in data blocks after the last incr backup. So PBM would store only the diffs for every next incr backup. For the restore, PBM would basically …

PBM-999: Add Incremental Backpus

---

pbm/archive/archive.go
pbm/backup/logical.go
pbm/oplog/restore.go
pbm/restore/logical.go
pbm/snapshot/dump.go

We can selectively restore unsharded collection(s) in sharded cluster, but mongos does not see the collections and their databases if these databases do not exist yet. For that, we restore (during snapshot restore and oplog replay stages) only the needed document(s) in config.databases on configsvr to make these collections/databases visible.
It also handles [movePrimary command](https://www.mongodb.com/docs/manual/reference/command/movePrimary/)

[PBM-962] Selective Backup/Restore for unsharded collections in sharded cluster

---

agent/snapshot.go
pbm/backup/backup.go
pbm/backup/physical.go
pbm/bcp_nodes_priority.go
pbm/pbm.go

Incremental backup history is stored by WiredTiger on the node not replset. So an `incremental && not_base` backup should land on the agent that made a previous (src) backup. Otherwise, the node won't be able to provide the diffs and will return an error.

PBM-999: start incr backup on the same node

---

pbm/restore/physical.go

Physical restore wasn't properly initialising the logger for storage. That caused panics when S3 storage tried to log some actions.
https://jira.percona.com/browse/PBM-1006

PBM-1006: fix panic during phys restore S3 retries

---

e2e-tests/cmd/pbm-test/main.go
e2e-tests/cmd/pbm-test/run_remapping.go
e2e-tests/docker/docker-compose-remapping.yaml
e2e-tests/functions
e2e-tests/pkg/pbm/pbm_ctl.go
e2e-tests/pkg/tests/sharded/cluster.go
e2e-tests/pkg/tests/sharded/test_remapping.go
e2e-tests/run-all
e2e-tests/run-remapping
pbm/restore/logical.go

When the logical backup is made by replicaset with a different name than the current one it is now posible to use that backup.
Changes include also refactor enabling the use of "e2e-ecosystem" for remapping tests. As a part of refactoring the following changes have been made:
- the ability to pass additional options to pbm restore command
- the ability to pass the name of the container with pbm agent
- new kind of tests (remapping) with dedicated docker-compose
Signed-off-by: ziollek <e.prace@gmail.com>

PBM-1003 Fix ability to restore with remapping replicaset names

---

pbm/oplog/restore.go
pbm/restore/logical.go

create collection commands are skipped because they have `db.$cmd`-like namespace

[PBM-1008] A specific collection cannot be restored from PITR if it did not exist in the full backup

---

Makefile

Add targets for building pbm-agent-entrypoint binary, so it could be installed via packages.

PBM-1018 add build/install target for pbm-agent-entrypoint

---

docker/Dockerfile.k8s

https://jira.percona.com/browse/PBM-941
This PR adds missing `pbm-agent-entrypoint` binary to the image

PBM-941: fix `Dockerfile.k8s`

---

pbm/archive/archive.go
pbm/pbm.go
pbm/pitr/pitr.go
pbm/restore/physical.go

Some more typos fixes in user facing messages.
Also one fix for a variable name (`s/predule/prelude/`)

Fix some more typos

---

cli/cli.go
cli/list.go
cli/status.go

```
$ pbm status -s backups
Backups:
========
FS  /opt/backups/pbm
Snapshots:
2023-02-01T15:57:59Z 294.52MB <incremental> [restore_to_time: 2023-02-01T15:58:01Z]
2023-02-01T15:57:08Z 46.10MB <incremental> [restore_to_time: 2023-02-01T15:57:10Z]
2023-02-01T15:53:17Z 525.80MB <incremental, base> [restore_to_time: 2023-02-01T15:53:19Z]
```
```
$ pbm list
Backup snapshots:
2023-02-01T15:53:17Z <incremental, base> [restore_to_time: 2023-02-01T15:53:19Z]
2023-02-01T15:57:08Z <incremental> [restore_to_time: 2023-02-01T15:57:10Z]
2023-02-01T15:57:59Z <incremental> [restore_to_time: 2023-02-01T15:58:01Z]
```

PBM-1035: mark incremental base backups in status and list

---

pbm/backup/physical.go

Sometimes the cursor can return files with an offset beyond the current file size. Such phantom changes shouldn't be copied. But save meta to have file size.
```
...
{
filename: '/data/db/collection-0-1152525642850732577.wt',
offset: Long("100663296"),
length: Long("16777216"),
fileSize: Long("385024")
},
{
filename: '/data/db/collection-0-1152525642850732577.wt',
offset: Long("117440512"),
length: Long("16777216"),
fileSize: Long("385024")
},
...
```

PBM-1046: incremental backup: handle phantom changes

---

Makefile

We met the error during pbm image build: 
```
12:03:36  GO111MODULE=on GOOS=linux go build -ldflags="-X github.com/percona/percona-backup-mongodb/version.gitCommit= -X github.com/percona/percona-backup-mongodb/version.gitBranch= -X github.com/percona/percona-backup-mongodb/version.buildTime=2023-02-07_08:03_UTC -X github.com/percona/percona-backup-mongodb/version.version=" -mod=vendor -tags gssapi -o ./bin/pbm ./cmd/pbm
12:03:37  error obtaining VCS status: exit status 128
12:03:37  	Use -buildvcs=false to disable VCS stamping.
```
As we can see from the message it can be fix by using -buildvcs=false flag. 
**Broken build:**
https://cloud.cd.percona.com/job/pbm-docker-build/497/console
**Successful build:**
https://cloud.cd.percona.com/job/pbm-docker-build/499/

K8SPSMDB-857 fix pbm build

---

agent/snapshot.go
pbm/config.go
pbm/restore/physical.go
pbm/rsync.go

For physical restores' internal restarts, PBM uses mongod from $PATH by default. This change allows setting custom mongod binary.
Plus added a check if mongod is available and if its version matches the version from the backup before any critical changes.
Added to the config:
```
restore:
mongodLocation: /path/to/mongod
mongodLocationMap:
"node01:27017": /path/to/mongod
"node03:27017": /another/path/to/mongod
```
If no `mongodLocation` is set, PBM will try `$PATH/mongod`. `mongodLocationMap ` redefines `mongodLocation` (and the defaults) for the particular nodes

PBM-1042: physical restore, ability to set mongod location

---

pbm/node.go
pbm/pbm.go
pbm/restore/physical.go

A `shardIdentity` document in `admin.system.version` collection on shards contains the config server connection string.
A `config.shards` on the config server contains information about shards.
This info should be updated during the restore with data from the target cluster. Otherwise, shards won't start after the restore if the target is a cluster with new (compared to the backup) IPs/hostnames

PBM-1047: fix physical restore to new sharded cluster

---

pbm/bsontypes.go
pbm/restore/physical.go

Arbiters should be ignored.
And node votes should be restored during reconfig.

PBM-979: fix phys restore with arbiter and non-voting nodes

---

pbm/pbm.go
pbm/restore/physical.go

The config server has to be shut down only after data shards. Otherwise, data shards may hang.

PBM-1053: phys restore: shutdown configsvr last

---

pbm/backup/physical.go

Phys backup while trimming datadir from the file path always added a slash to the trim prefix. In case datadir was set with a tailing slash it led to a double slash and datadir wasn't trimmed at all (`Trimprefix("/data/db/file1", "/data/db//")`). Therefore in the backup's meta such files contain datadir and the restore would put them in a subdirectory inside datadir, "/data/db/data/db/file1" instead of "/data/db/file1".
This change fixes it.

PBM-1058: fix phys backups on datadirs with tailing /

---

pbm/config.go
pbm/storage/s3/s3.go

Added config option:
```
storage:
s3:
credentials:
session-token: <string>
```
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

PBM-1060: add ability to use tmp creds with AWS S3 storage

---

agent/agent.go
cmd/pbm-agent/main.go
e2e-tests/docker/docker-compose-rs.yaml
e2e-tests/docker/docker-compose.yaml
pbm/log/log.go
pbm/restore/physical.go

We shutdown mongod at the early stages of physical restores. Hence PBM logs are being written only to stderr since. It may lead to losing the logs (if agents' stderr isn't captured or isn't stored for long enough). Plus gaps in `pbm logs`.
This commit adds a log buffer for physical restores. The buffer will dump it's content to the storage on restore finish (whether it's successful or not). It also dumps content and reset buffer when logs size hist a certain limit (1 Mb).
Each log message is stored in JSON format for further automation (adding logs to pbmLogs druting pbm --force-resync, PMM integration etc).

PBM-778: add log buffer for phys restore

---

e2e-tests/docker/docker-compose-rs.yaml
packaging/conf/pbm-conf-reference.yml
pbm/backup/physical.go
pbm/restore/pbm_1058_test.go
pbm/restore/physical.go

Checks if dbpath exists in the file name  and cut it from destination. We suppose that "journal/" will always be present in the backup and it is always in the dbpath root and doesn't contain subdirs, only files.

PBM-1058: fix affected backups during restore

---

packaging/debian/install
packaging/debian/rules

It is very important (from the legal point of view) to distribute the license together with binaries.

add the license file to the deb package

---

cli/backup.go
pbm/restore/logical.go
pbm/restore/physical.go
pbm/version.go
version/version.go

Incremental backups made on PBM pre v2.1.(incremental backups tech preview) are incompatible with  v2.1.0+ (incremental backups GA)
Check, and for incompatible backups:
- mark in `pbm status`: 
```
2023-03-22T15:19:47Z 365.04KB <incremental> [incompatible: backup version (v2.0.4) is not compatible with PBM v2.1.0-dev] [2023-03-22T15:19:49Z]
2023-03-22T15:19:11Z 402.10KB <incremental, base> [incompatible: backup version (v2.0.4) is not compatible with PBM v2.1.0-dev] [2023-03-22T15:19:13Z]
```
- skip in `pbm list`
- don't start restore with: 
``` ... error: backup version (v2.0.4) is not compatible with PBM v2.1.0-dev ```

PBM-1069: check for incremental backups compatibility

---

e2e-tests/docker/docker-compose-rs.yaml
pbm/restore/physical.go

Incremental $backupCusor returns collections that were created but haven't ended up in the checkpoint yet in the format if they don't belong to this backup (see PBM-1063). PBM doesn't copy such files. But they are already in WT metadata. PSMDB (WT) handles this by creating such files during the start. But fails to do so if it runs with `directoryPerDb` option. Namely fails to create a directory for the collections. So we have to detect and create these directories during the restore.

PBM-1063: handle directoryPerDB for incremental backups 

---

cli/backup.go
cli/backup_test.go
cli/list.go
cli/status.go
pbm/backup/backup.go
pbm/node.go
pbm/pbm.go
pbm/restore/logical.go

1. store FCV in backup metadata
2. show the FCV in `describe-backup`
3. print warning in logs during restore when FCV is not the same. if there is no FCV in the backup meta, use `major.minor` version.
4. show an error in `pbm status` when FCV is different. hide such backups in `pbm list`

[PBM-1066] warn about incompatible FCV/mongo versions

---

agent/agent.go
cli/cli.go
cli/delete.go
pbm/backup/list.go
pbm/oplog/oplog.go
pbm/pbm.go

pbm cleanup --older-than="$UTC_OR_DURATION" command deletes backups and oplog with restore time less than the UTC_OR_DURATION value.
the UTC_OR_DURATION value can be one of the following formats:
- yyyy-mm-dd            (`2018-07-23`)
- yyyy-mm-ddThh:mm:ss   (`2018-07-23T13:25:01`)
- XXd                   (`30d` or `90d` or `180d`) [only days is supported]
It prints list of backups and oplog ranges and asks for confirmation. (note: oplog ranges are grouped by replset/shard name)
A user can confirm in advance with `--yes/-y` flag, so the command will run the cleanup immediately without printing the backups/oplog list.
The cleanup is done by an agent. CLI only prints the list and asks for confirmation. However, CLI can wait for the agent result.
The `--wait/-w` flag can be used to waiting …

[PBM-850] pbm cleanup command

---

pbm/pbm.go
pbm/rsync.go
pbm/snapshot/restore.go

Preserving of pbmBackups and pbmPITRChunks during resync is redundant. As storage is the source of trues anyway. And these preserved data had been never used or requested. But copying pbmPITRChunks slows resync down ALOT if there is a quite amount of chunks.

PBM-951: drop pbm*.old collections

---

cli/oplog.go
cli/restore.go
pbm/rsync.go

1. Parsing of the restore meta and `pbm restore -w` now properly reports errors when all nodes have failed but the replica set and cluster status weren't changed. This may happen when all nodes have failed with an error but they can't set the replica set and cluster statuses to error as we have partlyDone status.
2. Parsing of the restore meta and `pbm restore -w` now properly handle situations when all nodes have died, hence hb not progressing.
3. Added message to the `pbm restore` output when it's run without -w:
```
...
Check restore status with: pbm describe-restore 2023-04-07T14:14:58.434144169Z -c </path/to/pbm.conf.yaml>
No other pbm command is available while the restore is running!
```

PBM-1070: cli improvements for physical restores

---

agent/snapshot.go
cli/backup.go
cli/backup_test.go
pbm/restore/physical.go
pbm/rs_map.go

- each agent copies files from "reversely" mapped source
- on configsvr:
- `config.databases` - `primaryShard` field
-  `config.chunks` - `shard` and `history.*.shard` fields

[PBM-1055] replset remapping for physical/incremental restore

---

pbm/snapshot/backup.go

on configsvr during selective backup, the authSource is set to "config" but should be always "admin"

[PBM-1095] fix authSource on configsvr

---

docker/Dockerfile
docker/Dockerfile.k8s

Fixes https://jira.percona.com/browse/PBM-1142.

[PBM-1142] Use UBI-based image for Go builder

---

README.md

There were four links in the README that didn't exist anymore and only showed a 404 or wrong pages.
I updated the links accordingly so that you end up on the right locations as well as showing the architecture picture again in the README:

Fixed broken links to old documentation references

---

agent/backup.go
agent/restore.go
cli/backup.go
pbm/backup/backup.go
pbm/backup/logical.go
pbm/backup/physical.go
pbm/config.go
pbm/pbm.go
pbm/pitr/pitr.go
pbm/storage/storage.go

```yaml
backup: 
timeouts: 
startingStatus: 60  # wait 1 minute before marking as a failure
```
`backup.timeouts.startingStatus` is _uint32_ value. `0` (zero) means to use the default (33s)
```bash
pbm config --set backup.timeouts.startingStatus=120
pbm config --set backup.timeouts.startingStatus=0
```

[PBM-1154] add backup.timeouts.startingStatus

---

pbm/config.go
pbm/storage/fs/fs.go

If `storage.filesystem.path` points to a symbolic link, PBM will resolve the actual path and be able to list/read the folder's content. Otherwise, it considers the path as a regular file and does not see any content in the linked folder.
However, it will not resolve any link inside the storage path.

[PBM-1147, PBM-885] support link for fs storage

---

cmd/pbm/config.go
cmd/pbm/main.go
internal/log/history.go
sdk/util.go

add `--wait`/`-w` flag to `pbm config` command for waiting for storage sync finish by an agent
```
$> pbm config --force-resync --wait
```
(have effect only with `--force-resync` flag)

[PBM-1187] Add --wait option to pbm config --force-resync

---

internal/config/config.go
internal/storage/azure/azure.go

add `storage.azure.endpointUrl` config field to customize default (`https://${account}.blob.core.windows.net`) Blob URL.

[PBM-1195] allow custom endpointUrl for Azure storage

---

cmd/pbm-speed-test/main.go
e2e-tests/cmd/pbm-test/main.go
e2e-tests/cmd/pbm-test/run.go
e2e-tests/cmd/pbm-test/run_physical.go
e2e-tests/pkg/tests/sharded/backuper.go
e2e-tests/pkg/tests/sharded/test_bounds_check.go
e2e-tests/pkg/tests/sharded/test_incremental_backup.go
e2e-tests/pkg/tests/sharded/test_oplog_replay.go
e2e-tests/pkg/tests/sharded/test_pitr_basic.go
pbm/restore/physical.go

[from docs](https://pkg.go.dev/math/rand#Seed):
> If Seed is not called, the generator is seeded randomly at program startup.
> Deprecated: As of Go 1.20 there is no reason to call Seed with a random value.

[linter] remove deprecated rand.Seed() calls

---

pbm/connect/connect.go
pbm/restore/physical.go

PR for https://perconadev.atlassian.net/browse/PBM-1159 .
It expands #911 with the ability to specify `WriteConcern` connection string option.
Example:
```jsx
mongodb://pbmuser:secretpwd@localhost:27017/?authSource=admin&w=1
```

PBM-799: Make WriteConcern option configurable

---

cmd/pbm-agent/agent.go
cmd/pbm-agent/backup.go
cmd/pbm/backup.go
cmd/pbm/main.go
pbm/backup/backup.go
pbm/backup/physical.go
pbm/backup/query.go
pbm/backup/storage.go
pbm/backup/types.go
pbm/ctrl/cmd.go
pbm/restore/physical.go
pbm/storage/azure/azure.go
pbm/storage/s3/download.go
pbm/storage/s3/s3.go
pbm/storage/storage.go
pbm/version/version.go
pbm/version/version_test.go
sdk/impl.go
sdk/sdk.go

https://jira.percona.com/browse/PBM-1252

[PBM-1252] keep list of physical files in storage

---

.github/workflows/ci.yml

[Docker compose v1 will be removed from GH runners on Apr, 1](https://github.com/actions/runner-images/issues/9557)

CI migrate to docker compose v2

---

cmd/pbm/main.go
cmd/pbm/restore.go
pbm/backup/logical.go
pbm/ctrl/cmd.go
pbm/restore/logical.go
pbm/restore/logical_test.go
pbm/util/sel.go
pbm/util/sel_test.go

PR for https://perconadev.atlassian.net/browse/PBM-1213
The feature expands logical restore command with the possibility to include database specific users and roles. 
When restoring specific database(s) from the full backup, it is possible to specify new `--with-users-and-roles` flag, and in that case database specific users&roles will be restored together with db related data.
Selective restore from full backup example:
```
$ pbm backup
Starting backup '2024-03-27T16:48:21Z'.......
$ pbm restore --ns="mydb1.*, mydb2.*" --with-users-and-roles 
```

PBM-1213: Selective Logical Restore with included Users&Roles

---

cmd/pbm/config.go
pbm/config/config.go
sdk/impl.go

PR for https://perconadev.atlassian.net/browse/PBM-1258

PBM-1258: Fix for unnecessary resync operation when applied config's storage params are the same

---

e2e-tests/docker/pbm.dockerfile
e2e-tests/docker/tests.dockerfile
packaging/scripts/mongodb-backup_builder.sh

Since golang 1.20, the exact version should be used in the download link (go1.20.0 instead of go1.20)

fix go1.22 download link in packaging

---

pbm/connect/connect.go
pbm/restore/logical.go

Fix for https://perconadev.atlassian.net/browse/PBM-1309
In this bug, pbm-agent wan't able to create (try to create) pbm related collections after restart of the agent in case when cluster doesn't have majority of data members.
Root cause is that Database.RunCommand api call doesn't apply read/write concerns specified in connection string (see documentation [here](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo@v1.15.0#Database.RunCommandCursor:~:text=This%20function%20does%20not%20obey%20the%20Database%27s%20readConcern%20or%20writeConcern.%20A%20user%20must%20supply%20these%20values%20manually%20in%20the%20user%2Dprovided%20runCommand%20parameter.)). This PR applies read/write concern from connection string to particular command (only 'create' command for now).

PBM-1309: PBM can't be started if RS doesn't have a majority

---

pbm/connect/connect.go

Fix for https://perconadev.atlassian.net/browse/PBM-1307
Validation for WriteConcern w=0 is added because PBM cannot operate in that mode.
If that value is specified within conn string, `pbm-agent` or `pbm-cli` will fail with following error:
```
Error: connect to mongodb: create mongo connection: invalid connection string option: WriteConcern without acknowledgment is not allowed (w: 0)
```

PBM-1307: Disallow WriteConcern for  unacknowledged write operation

---

cmd/pbm-agent/agent.go
pbm/connect/connect.go

Fix for https://perconadev.atlassian.net/browse/PBM-1308 .
Following validation are added:
```
mongodb://pbmuser:test1234@0.0.0.0:30001/?authSource=admin&w=1
mongodb://pbmuser:test1234@0.0.0.0:30001/?authSource=admin&w=1&readConcernLevel=majority
-----
Exit: connect to PBM: create mongo connection: invalid connection string option: ReadConcern majority and WriteConcern 1 is not allowed
```
```
mongodb://pbmuser:test1234@0.0.0.0:30001/?authSource=admin&w=1&readConcernLevel=available
mongodb://pbmuser:test1234@0.0.0.0:30001/?authSource=admin&w=1&readConcernLevel=snapshot
mongodb://pbmuser:test1234@0.0.0.0:30001/?authSource=admin&w=1&readConcernLevel=linearizable
mongodb://pbmuser:test1234@0.0.0.0:30001/?authSource=admin&w=1&readConcernLevel=abc
-----
Exit: connect to PBM: create mongo …
```

PBM-1308: Improve read/write concern validation

---

cmd/pbm-agent/pitr.go

When the `pbm-agent` (during the pitr procedure) fails on reading the storage config it may get locked out of starting the slicer (which results in missing pitr data for a given replicaset in sharded cluster).
Each node is blocked at: https://github.com/percona/percona-backup-mongodb/blob/v2.5.0/cmd/pbm-agent/restore.go#L183-L185
Release the lock before exiting the function to allow another node to continue the slicing.

PBM-1343: Release the lock when failed to read the storage config

---

e2e-tests/README.md
e2e-tests/functions
e2e-tests/run-new-cluster

After upgrade of Docker I had following issue:
https://docs.docker.com/desktop/release-notes/#known-issues
so I decided to upgrade to Compose V2

Migrate e2e-tests to Docker Compose V2

---

cmd/pbm-agent/pitr.go
pbm/prio/priority.go
pbm/slicer/slicer.go

PR for https://perconadev.atlassian.net/browse/PBM-557
PBM monitors if RS member that is doing PITR slicing has decreased priority.
This is only applied when PITR priority is based on cluster topology (hidden, secondary, primary rules).
In such a case, PBM restarts election process and elects new PITR slicing members, according to new priority configuration.

PBM-557: PITR slicing could end up on primary node

---

pbm/storage/fs/fs.go

Whilst trying to understand historic cases where we have seen BSON deserialisation errors, I realised it was possible for filesystem writes to be incomplete, but be unable to determine the fact.  In particular, once an oplog file exists on the filesystem, it is assumed to be complete even though the write may have been interrupted.
This change performs all filesystem writes to a temporary file in the same directory and does a rename once the sync has returned.
In the event of a failure, calling Close() on the same file handle does not cause an error because the deferred call discards the error.
I do not believe non-filesystem storage are affected by this problem, as the providers have other checks in place to ensure the upload completed.

PBM-1329 Write to temporary file name and sync before renaming

---

pbm/storage/s3/s3.go

In order to be able to define server-side encryption with Amazon S3 managed keys (SSE-S3) user needs to set storage.s3.serverSideEncryption.sseAlgorithm to AES256 option.
https://github.com/aws/aws-sdk-go/blob/main/service/s3/api.go#L45783

PBM-1376. Add support for SSE-S3 for S3 providers

---

cmd/pbm-agent/agent.go
cmd/pbm-agent/backup.go
cmd/pbm-agent/pitr.go
pbm/defs/defs.go
pbm/topo/agent.go
pbm/topo/topo.go

PR for https://perconadev.atlassian.net/browse/PBM-1057
In the context of this PR, non-suitable agents for _Backup_ and _PITR_ are:
- agents with node status different than _PRIMARY_ or _SECONDARY_ (e.g. _STARTUP2_ for initial sync from the Jira ticket)
- agents with _Arbiter_ or _Delayed_ node
- agents with node's replication lag
This PR filters out non-suitable agents from:
- _Backup_ nomination process
- _PITR_ nomination process

PBM-1057: Forbidden running Backup & PITR on non-suitable agents

---

cmd/pbm/main.go
cmd/pbm/restore.go

PR for https://perconadev.atlassian.net/browse/PBM-1338
`start` and `finish` fields display `restore` start and finish time. Field `finish` is displayed only in case of successfully finished restore (`status: done`).
```
$ pbm describe-restore 2024-09-03T07:48:59.389263417Z
name: "2024-09-03T07:48:59.389263417Z"
opid: 66d6bf6b4134f541bae6f571
backup: "2024-09-03T07:37:16Z"
type: logical
status: done
start: "2024-09-03T07:48:59Z"
finish: "2024-09-03T07:50:06Z"
last_transition_time: "2024-09-03T07:50:06Z"
replsets:
- ...
```

PBM-1338: Restore Start/Finish time for `describe-restore` command

---

cmd/pbm-agent/agent.go
cmd/pbm-agent/backup.go
cmd/pbm-agent/main.go
cmd/pbm-agent/oplog.go
cmd/pbm-agent/restore.go
cmd/pbm/backup.go
cmd/pbm/main.go
cmd/pbm/restore.go
pbm/archive/archive.go
pbm/backup/backup.go
pbm/backup/logical.go
pbm/ctrl/cmd.go
pbm/restore/logical.go
pbm/snapshot/backup.go
pbm/snapshot/dump.go
pbm/snapshot/restore.go

The behavior of v2.6.0 and early:
`--dump-parallel-collections` flag (`pbm-agent run` command) (or `PBM_DUMP_PARALLEL_COLLECTIONS` env var) control number of parallel collections to backup. This number is saved in the backup archive metadata file (`concurrent_collections` field in `$BACKUP/$REPLSET/metadata.json`). By default, it is set to half of the number of logical CPUs. During restore, mongotools uses the value to set the number of parallel collections to restore (it means, it depends on the actual value in a backup).
mongotools prints these values during backup (`dumping up to 4 collections in parallel`) and restore (`restoring up to 4 collections in parallel`). It is visible by `pbm logs -s D`.
New behavior:
Added new flag `--num-parallel-collections` (help msg: Number of parallel …

[PBM-1312] allow to control max number of parallel collections

---

pbm/backup/backup.go

PR for https://perconadev.atlassian.net/browse/PBM-1369
In the case of the lost `pbm-agent`, [setClusterLastWriteImpl](https://github.com/percona/percona-backup-mongodb/blob/5bb76dacbaf1856074415230d7964c428141795e/pbm/backup/backup.go#L664-L679) might have an endless loop, it the case when `last_write_ts` is not written on RS level.
This fix solves the problem by checking if `pbm-agent` is lost within the same loop.

PBM-1369: Fix never ending backup after agent is lost

---

e2e-tests/pkg/tests/sharded/test_backup_cancellation.go

fixed by https://github.com/percona/percona-backup-mongodb/pull/1010

PBM-823: enable leftover files check for cancelled backup

---

e2e-tests/cmd/pbm-test/run.go
e2e-tests/pkg/tests/sharded/backuper.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
e2e-tests/pkg/tests/sharded/test_oplog_replay.go
e2e-tests/pkg/tests/sharded/test_pitr_basic.go
e2e-tests/pkg/tests/sharded/test_timeseries.go

https://github.com/percona/percona-backup-mongodb/pull/999 prevents running op when a lock has already been acquired. it is not possible to delete backups or change config (e.g. enable PITR) if there is another operation in progress

PBM-1394: fix tests according to PBM-1316

---

pbm/storage/s3/s3.go

This change allows to retrieve remote credentials not only from EC2, but also from ECS and EKS roles.
See https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html for details about EKS Pod Identities.

Use RemoteCredsProvider from aws default stack

---

pbm/backup/backup.go
pbm/backup/query.go
pbm/backup/storage.go
pbm/resync/rsync.go

backup status can be set to done in db meta before the meta is written to storage. if the write fails, no meta will be available on storage. storage resync will delete backup meta from db and won't see it on storage.

PBM-1114: check backup files before mark it as done

---

pbm/oplog/backup.go
pbm/storage/storage.go

`storage.Upload()` with already canceled context can trigger data race warning (https://github.com/percona/percona-backup-mongodb/blob/v2.6.0/pbm/storage/storage.go#L179)

PBM-886: sync channel set/unset/close ops

---

cmd/pbm-agent/setup.go
pbm/restore/physical.go

PR for https://perconadev.atlassian.net/browse/PBM-1391
After physical restore with PITR, all PSMDB secondary nodes fail with the fatal error:
```
{"t":{"$date":"2024-09-12T06:12:55.515+00:00"},"s":"F",  "c":"ASSERT",   "id":23081,   "ctx":"ReplWriterWorker-6","msg":"Invariant failure","attr":{"expr":"!needsRenaming || allowRenameOutOfTheWay","msg":"Current collection name: (None), UUID: 0ea5a363-872c-4380-87c6-ff426f0b0a85. Future collection name: admin.pbmPITR","file":"src/mongo/db/catalog/create_collection.cpp","line":835}}
{"t":{"$date":"2024-09-12T06:12:55.515+00:00"},"s":"F",  "c":"ASSERT",   "id":23082,   "ctx":"ReplWriterWorker-6","msg":"\n\n***aborting after invariant() failure\n\n"}
{"t":{"$date":"2024-09-12T06:12:55.515+00:00"},"s":"F",  "c":"CONTROL",  "id":6384300, …
```

PBM-1391: Enabling PITR after physical restore causes PSMDB to crash

---

cmd/pbm-agent/agent.go

When analyzing PBM's logs, it is not possible to correlate the backup's name with the backup's OPID. That is typically needed when analyzing locks and PITR execution. This PR adds a line that correlates them, e.g:
```
2024-09-26T15:27:56Z I [rs2/rs202:27017] got command backup [name: 2024-09-26T15:27:55Z, compression: none (level: default)] <ts: 1727364475>, opid: 66f57d7b0940491a6d4aef8a
```

PBM-1381: Log correlation between Backup Name and OPID

---

cmd/pbm-agent/agent.go
cmd/pbm-agent/main.go
pbm/ctrl/recv.go
pbm/topo/agent.go

on startup, pbm-agent updates his heartbeat immediately then every 60 seconds it checks if its heartbeat is updated unexpectedly. this happens when two agents update the same heartbeat concurrently.

PBM-397: warn about parallel agent for the same node

---

cmd/pbm-agent/backup.go
cmd/pbm-agent/oplog.go
cmd/pbm-agent/restore.go
pbm/config/config.go
pbm/restore/logical.go

added `backup.numParallelCollections` and `restore.numParallelCollections` fields to config to control the default values of the commands. they can be overwritten by the commands flag.

PBM-1400: add num-parallel-collections to pbm config

---

cmd/pbm-agent/agent.go
cmd/pbm-agent/delete.go
cmd/pbm-agent/pitr.go
cmd/pbm-agent/profile.go
cmd/pbm-agent/restore.go
cmd/pbm-agent/resync.go
cmd/pbm-speed-test/main.go
cmd/pbm/backup.go
cmd/pbm/main.go
cmd/pbm/oplog.go
cmd/pbm/restore.go
cmd/pbm/status.go
e2e-tests/cmd/ensure-oplog/main.go
e2e-tests/pkg/pbm/mongo_pbm.go
e2e-tests/pkg/tests/sharded/test_backup_cancellation.go
pbm/backup/backup.go
pbm/backup/delete.go
pbm/backup/logical.go
pbm/restore/logical.go
pbm/restore/physical.go
pbm/resync/rsync.go
pbm/storage/azure/azure.go
pbm/storage/s3/s3.go
pbm/util/storage.go
sdk/impl.go
sdk/sdk.go

PR for https://perconadev.atlassian.net/browse/PBM-1211
PBM's multiple endpoint feature enables possibility to specify different endpoint urls for the different cluster members, but all of them should point to the same cloud storage. 
Supported storage types are: S3 and Azure.
Example for possible configuration:
```
storage:
type: s3
s3:
endpointUrl: http://S3:9000
endpointUrlMap:
"node01:27017": "did.socf.s3.com"
"node03:27017": "123.12.1.202"
...
```

PBM-1211: Multi-endpoint feature

---

cmd/pbm/diagnostic.go
cmd/pbm/main.go
cmd/pbm/status.go
pbm/log/history.go
sdk/sdk.go
sdk/util.go

```bash
> pbm help diagnostic
usage: pbm diagnostic --path=PATH [<flags>]
Create diagnostic report
Flags:
--path=PATH                Path where files will be saved
--opid=OPID                OPID/Command ID
--name=NAME                Backup or Restore name
```
`--name` or `--opid` must be provided. it writes files inside `--path`. if `--path` does not exit, create it (like `mkdir -p`).
files:
- $(OPID).report.json (describes cluster)
- $(OPID).log (log (JSON) between command/operation start and end)
- $(OPID).backup.json (backup meta)
- $(OPID).restore.json (restore meta)
example of `672a0d4e2a59c1f46f628873.report.json`:
```jsonc
{
"cluster_time": {
"$timestamp": {
"t": 1730813162,
"i": 1
}
},
"command": {
"cmd": "backup",
"backup": {
"type": "logical",
"base": false,
"name": …
```

PBM-887: add diagnostic command

---

cmd/pbm/restore.go
cmd/pbm/restore_test.go
pbm/oplog/restore.go
pbm/restore/logical.go
pbm/restore/restore.go

PR for https://perconadev.atlassian.net/browse/PBM-1422
PR #1040 allows restore and cloning collection, but doesn't apply oplog entries that happened during the backup, neither it supports PITR feature. 
The PR expands the cloning feature with two additional use cases:
- applying oplog entries that happened during the backup 
- applying PITR entries that are stored within PITR chunks
In case of cloning, applying oplog entries means:
- selecting entries that are relevant for collection cloning source (`--ns-from`)
- applying selected entries but with the different namespace (`--ns-to`)
- following types of oplog operation are processed: `insert`, `update`, `delete` ops, and index related DDL ops
- all other DDL related ops are ignored

PBM-1422: Adjust Oplog and PITR to support cloned collection

---

cmd/pbm-agent/main.go
cmd/pbm/main.go
pbm/log/discard.go
pbm/log/log.go
pbm/log/logger.go

PR for https://perconadev.atlassian.net/browse/PBM-1226
In the current version, PBM supports sending diagnostic logging information to:
- database collection `admin.pbmLogs`: PBM's central logging which includes logs from all pbm-agents,
- `stderr` for every pbm-agent.  
This PR allows sending logging information into an arbitrary log file instead of `stderr`. Each pbm-agent creates the log file at the specified path for that purpose.
Logging configuration is possible to define using:
- pbm-agent's options
- environment variables
```
$ pbm-agent help                                                                                                                                                 
Flags:
...
--log-path="/dev/stderr"  Path to file
--log-json                Enable JSON output …
```

PBM-1226: `logpath` option for pbm-agent

---

pbm/oplog/restore.go

PR for https://perconadev.atlassian.net/browse/PBM-1444
This PR expands cloning collection feature with logic for processing `create` and `drop` operations from the oplog.
It uses the same approach as selective restore has.
In previous PR #1046 those 2 commands were just ignored.

PBM-1444: Cloning for create/drop ops

---

.github/workflows/codecov.yml

On codecov it's required to have 'branch context' to be able to observe the general trend over time. When report is sent only on PR, it's possible to switch over different branches, but no possibility to select one for branch context of data in coverage dashboard.

CI. Send report to codecov for dev branch

---

cmd/pbm-agent/restore.go

- to avoid performance degradation we revert the default to 10

PBM-1414 revert the default for numInsertionWorkers to 10

---

cmd/pbm-agent/main.go
pbm/log/logger.go
pbm/log/logger_test.go

Fix for https://perconadev.atlassian.net/browse/PBM-1460
`pbm-agent` should handle log-related settings even in the early phase of running, when the DB connection hasn't been established yet, and even when connecting to DB fails. This PR fixes such a situation because it currently places all logs into `stderr`.

PBM-1460: Connection error isn't written to PBM log despite log-path option is specified

---

pbm/oplog/restore.go
pbm/restore/logical.go
pbm/snapshot/restore.go

Fix for https://perconadev.atlassian.net/browse/PBM-1459
PBM creates an index catalog during the snapshot restore phase. This PR changes the approach of handling changes within the index catalog:
- Previously PBM cloned indexes after the PITR procedure from the index catalog.
- With this PR, cloning is performed during the snapshot restore phase, as well as, during the PITR phase. Logic for cloning indexes after PITR phase is removed.

PBM-1459: PBM ignores index removal during selective PITR restore with name remapping

---

e2e-tests/cmd/pbm-test/run_physical.go
e2e-tests/pkg/pbm/clock_skew.go
e2e-tests/pkg/tests/sharded/cluster.go
e2e-tests/pkg/tests/sharded/test_clock_skew.go

In PSMDB 8.0 tcmalloc is used by default, however since both tcmalloc and libfaketime use interceptors, it causes tcmalloc to get into a dead lock, hence PSMDB is just getting stuck. Since there is no way to fix PSMDB, use of libfaketime is disabled during physical restore.

PBM_tests. Unset LD_PRELOAD on physical restore to prevent PSMDB 8.0 getting stuck

---

pbm/backup/logical.go
pbm/backup/logical_test.go
pbm/restore/logical.go

PR for https://perconadev.atlassian.net/browse/PBM-1465
PR fixes the following two different issues within the Config Shard environment:
- selective backup didn't dump non-config namespaces on Config Shard RS
- during the restore procedure, oplog replay step didn't apply entries for non-config namespace on Config Shard RS

PBM-1465: Selective backup/restore for sharded collections fails for setups with config shards

---

cmd/pbm/delete.go
cmd/pbm/main.go

PR for https://perconadev.atlassian.net/browse/PBM-1466
The PR replaces the use of kingpin by Cobra and Viper.

PBM-1466 - Remove kingpin dependency from pbm cli

---

cmd/pbm-agent/main.go
pbm/archive/backup.go
pbm/archive/conv.go

if only 1 CPU - we'll dump at lest 1 collection at te time

PBM-14780 Adjust concurrentCollections for backup operation for single CPU

---

cmd/pbm-agent/restore.go
pbm/backup/backup.go
pbm/topo/topo.go

PR for https://perconadev.atlassian.net/browse/PBM-1452
With this feature, PBM stops `balancer` at the beginning of the `restore` procedure:
- it does it for `logical` and `physical` restore
- stopping balancer command is always executed exclusively by Config Server Primary node

PBM-1452: Stop balancer automatically during restore

---

cmd/pbm-agent/restore.go
pbm/backup/backup.go
pbm/topo/cluster.go
pbm/topo/topo.go

PR for https://perconadev.atlassian.net/browse/PBM-1452
PR expands stopping `balancer` procedure with additional criteria. 
When checkin if balancer is stopped PBM checks following `balancer status` fields:
- `mode` to find out if balancer is running (was checked also before)
- `inBalancerRound` to detect currently active balancer round (new criteria)

PBM-1452: Expand procedure for disabling balancer

---

pbm/restore/physical.go
pbm/restore/physical_test.go

PR for https://perconadev.atlassian.net/browse/PBM-1507
This feature improves the resiliency of the physical restore procedure by:
- adding an alternative dbpath directory (`.fallbacksync`), which will be used in case of failed restore
- in sharded cluster environment, applying files from `.fallbacksync` dir will be done only in case when the restore procedure finishes with status `error`
- if the restore procedure finishes in status `done` or `partalyDone`, `.fallbacksync` db dir is not applied
PR also improves cluster status after the restore procedure by setting appropriate status in case of an error during the restore procedure.

PBM-1335: Fallback dbpath for physical restore

---

pbm/topo/cluster.go
pbm/topo/topo.go

PR for https://perconadev.atlassian.net/browse/PBM-1512
When reporting cluster members (`topo.ClusterMembers`) PBM doesn't include hidden/passive members due to the bug:
- for RS topology, it uses `isMaster.hosts` command which [doesn't include hidden/passive members](https://www.mongodb.com/docs/manual/reference/command/hello/#mongodb-data-hello.hosts)
- for sharded cluster topology, it uses `getShardMap.map` command which, again doesn't include hidden/passive members
Provided fixes for RS and sharded cluster use both commands above, with a combination of `replSetGetStatus` command to report hidden/passive members for the whole cluster.

PBM-1512: Unable to take physical backup in mixed deployments

---

pbm/snapshot/restore.go

Make sure defined `config` collections are excluded correctly.

PBM-1523 Fix exclude-slices merging

---

pbm/restore/logical.go

Make sure to not skip other databases than 'admin'.
It aims to solve following issues:
1. When restoring a namespace with problematic database name (for example `administration.*`) it makes the database filter empty and ALL the users are restored (includes users from other databases).
2. When restoring multiple namespaces, including the problematic one (for example `administration.*,somedb.*`) it skips the`administation` database in filters and as a result the user related to this database is NOT restored (the other ones are).

PBM-1522 Check full db name instead of a prefix

---

pbm/restore/phys/phys.go
pbm/restore/physical.go
pbm/storage/download.go
pbm/storage/gcs/download.go
pbm/storage/gcs/gcs.go
pbm/storage/s3/download.go
pbm/storage/s3/s3.go

PR for https://perconadev.atlassian.net/browse/PBM-1506
It reintroduces the ability to download a single large file in parallel for Google Cloud Storage (GCS) after introducing Google's native SDK.
Users can speed up restores by using multiple workers to download big files in parallel. With these changes, it will be available for S3 and GCS but has been made with consideration of supporting additional storage types in the future.
The changes reuse the existing logic from the S3 download module.

PBM-1506 GCS support concurrent downloading

---

pbm/restore/selective.go

PR for https://perconadev.atlassian.net/browse/PBM-1482
PR fixes two issues:
- When dealing with selective restore and processing `config` db related collections, backup files were not closed, which implies possible resource leaks and deadlock in case when S3 compatible storage is used (while using `io.Pipe`).
- When processing `config.chunks` database, not all documents were processed, only the first batch of documents was processed.

PBM-1482: Selective Restore hangs on oplog replay and doesn't finish

---

pbm/restore/physical.go
pbm/storage/azure/azure.go
pbm/storage/blackhole/blackhole.go
pbm/storage/fs/fs.go
pbm/storage/gcs/gcs.go
pbm/storage/s3/s3.go
pbm/storage/storage.go

PR for https://perconadev.atlassian.net/browse/PBM-1531
PR fixes deadlock issue that happens during the physical restore. 
During physical restore PBM stores logs on the backup storage (db is down). 
Logger is shared by many goroutines so it holds mutex to provide synchronized write access, during which logger writes to the storage using the PBM's storage API.
PBM's storage API started to add log entries in v2.6, e.g.:
```
uploading "...rs.starting" [size hint: 10 (10.00B); part size: 10485760 (10.00MB)]
```
While doing that, it tries to do lock of the same mutex, and that's deadlock.
This fix skips logging from PBM's storage API (log entry above) only during storing logger entries as part of physical restore.
It is applied for AWS S3 and Azure (for FS and GCS, PBM doesn't log).

PBM-1531: Fix deadlock during physical restore file copying

---

pbm/backup/logical.go

This PR addresses an issue where the configured `maxUploadParts` setting was being honored during multipart upload but ignored during part size calculation for instances where the size was unknown, leading to upload failures on oplog slices.
Estimate oplog slice size using bytes/sec × duration with extra growth and a 1 GiB minimum to avoid exceeding multipart limits. Ensures partSize is computed reliably, preventing upload failures.

PBM-1439 - Fix backup failure: MaxUploadParts exceeded

---

pbm/storage/gcs/download.go
pbm/storage/gcs/gcs.go
pbm/storage/gcs/google_client.go
pbm/storage/gcs/hmac_client.go

This PR updates the getPartialObject implementations for Google Cloud Storage (GCS) and MinIO (via HMAC) to match the buffering strategy already used by AWS S3. Previously, both backends returned open io.ReadCloser streams from their respective SDKs. This was already present in the original GCS implementation.

PBM-1498 hmac support for gcs fix

---

e2e-tests/cmd/pbm-test/run.go
e2e-tests/pkg/tests/sharded/cmd.go
e2e-tests/pkg/tests/sharded/test_cleanup_full_restore.go
e2e-tests/pkg/tests/sharded/trx.go
pbm/defs/defs.go
pbm/restore/logical.go

PR for https://perconadev.atlassian.net/browse/PBM-1487
In the sharded cluster environment, PBM needs to perform logical restore on the clean cluster (databases that are part of the backup are not present in the target cluster).
In the case when cluster is not clean, and logical restore is performed, there is chance that mongodb will rise `Time monotonicity violation` error due to cache's consistency model validation.
To fix that issue, this PR adds the following logic to PBM logical restore procedure:
- PR targets only sharded cluster full logical restore and full logical restore with PITR.
- PR introduces the `cleanup phase` as part of the logical restore. During that phase, PBM  drops all databases that are present in the backup, and by doing that, it makes the cluster clean for the …

PBM-1487: Cleanup cluster before logical restore

---

pbm/restore/physical.go
pbm/restore/physical_test.go

PR for https://perconadev.atlassian.net/browse/PBM-1553
This fix improves how PBM does `mongod` restarts during physical restore:
- When waiting for `mongod.lock` file, PBM has global timeout for that operation.
- After `mongod.lock` is released, PBM waits for the port to be available, and only after that continues. This prevents any port conflicts when PBM attempts to restart `mongod` again.
- It introduces port waiting timeout.

PBM-1553: Improve mongod restart procedure during physical restore

---

pbm/restore/physical.go
pbm/restore/physical_test.go

PR for https://perconadev.atlassian.net/browse/PBM-1553
This fix improves how PBM handles internal `mongod` logs during the physical restore procedure:
- After physical restore PBM keeps all internal mongod logs (`pbm.restore.log*`) within `dbpath` dir, no matter whether it was successful or failed one.
-  Before new physical restore, internal `mongod` logs are removed as part of wipe-up procedure.

PBM-1553: Improve mongod logging during physical restore

---

cmd/pbm-agent/restore.go

`addRestoreMetaWithError` now formats the message once, so both the log and restore-metadata have the full error text instead of the `%v` placeholder. This only affects error reporting, behavior stays the same.

PBM-1499 Unformatted error in restore metadata

---

cmd/pbm-agent/resync.go
cmd/pbm/config.go
cmd/pbm/main.go
pbm/ctrl/cmd.go
pbm/resync/rsync.go
sdk/impl.go

Renames `--skip-restores` (and related fields/params) to `--include-restores`. Default behavior now syncs only the latest restore metadata file, pass `--include-restores` to parse them all.
Also discussed with Operators team, which mentioned that it seems OK for them.

PBM-1514 improve resync performance updates

---

pbm/restore/physical.go
pbm/restore/physical_test.go

PR for https://perconadev.atlassian.net/browse/PBM-1550
PR fixes physical restore's `close` logic in the way, that `cleanup phase` is applied only when `dbpath` dir was changed.

PBM-1550: Physical restore started without conditions

---

.golangci.yml

Align linters with the ones on dev and update config for V2:
- `stylecheck` linter is now part of `staticcheck`
- `typecheck` is removed since it is no longer treated as linter

Align linters

---

cmd/pbm-agent/pitr.go
pbm/backup/physical.go
pbm/config/config.go
pbm/config/config_test.go
pbm/storage/azure/azure.go
pbm/storage/gcs/gcs.go
pbm/storage/s3/s3.go

PR for https://perconadev.atlassian.net/browse/PBM-1564
During the incremental backup procedure, PBM must verify that all backup increments are stored on the same storage. The PR makes storage identity checks more flexible by only comparing storage properties that identify the storage (e.g. `region` or `bucket` name, `prefix` path ...) and ignoring all other settings (e.g. credentials).

PBM-1564: Incremental backup fails with "source backup is stored on a different storage"

---

Makefile
cmd/pbm-agent/main.go
cmd/pbm-speed-test/main.go
cmd/pbm/main.go
e2e-tests/docker/pbm.dockerfile
pbm/util/completion.go

Add Cobra-based shell autocompletion for Bash and Zsh to pbm, pbm-agent, and pbm-speed-test.
Example usage:
To enable completion for your Bash session:
$ source <(pbm completion bash)
To enable completion for your Zsh session:
$ source <(pbm completion zsh)

Add support for shell completion

---

e2e-tests/pkg/pbm/pbm_ctl.go
e2e-tests/pkg/tests/sharded/test_dr_restart_agents.go
e2e-tests/run-new-cluster

[![PBM-1401](https://badgen.net/badge/JIRA/PBM-1401/green)](https://jira.percona.com/browse/PBM-1401) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Update expected error message to fix test failure due to:
`ERROR: wrong state of the backup 2025-06-23T06:04:33Z. Expect: error/some of pbm-agents were lost during the backup|...convergeCluster: lost shard... Got: error/set cluster last write ts: lost shard rs1, last beat ts: 1750658674`
[PBM-1401]: https://perconadev.atlassian.net/browse/PBM-1401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

E2E tests. Add wait flag for storage resync and update expected error message

---

pbm/oplog/restore.go
pbm/oplog/restore_test.go

[![PBM-1497](https://badgen.net/badge/JIRA/PBM-1497/green)](https://jira.percona.com/browse/PBM-1497) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PBM-1497]: https://perconadev.atlassian.net/browse/PBM-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
PR ensures that the `balancer` will not be started during the PITR chunks applying phase within the PBM's `restore` procedure.
When the balancer is started within the PITR restore procedure, it can happen that the balancer and PBM procedure concurrently modify the same documents, which …

PBM-1497: Exclude balancer ops during PITR

---

cmd/pbm/main.go

[![PBM-1569](https://badgen.net/badge/JIRA/PBM-1569/green)](https://jira.percona.com/browse/PBM-1569) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This PR adds validation for restore command arguments.
These scenarios were taken into account:
```
pbm restore [backupname]
pbm restore --time ...
pbm restore --external
```
[PBM-1569]: https://perconadev.atlassian.net/browse/PBM-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PBM-1569 Validation error message for pbm restore

---

pbm/defs/defs.go
pbm/oplog/restore.go
pbm/oplog/restore_test.go
pbm/restore/logical.go
pbm/restore/logical_cfgsvr_full.go
pbm/restore/restore.go
pbm/restore/selective.go
pbm/snapshot/restore.go
pbm/topo/node.go

[![PBM-1583](https://badgen.net/badge/JIRA/PBM-1583/green)](https://jira.percona.com/browse/PBM-1583) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
After the logical restore, `mongos` might report the following issue due to the wrong version of `config.system.sessions` collection:
```
{"t":{"$date":"2025-08-07T07:49:42.739+00:00"},"s":"F",  "c":"CONTROL",  "id":6384300, "svc":"R", 
"ctx":"CatalogCache-2","msg":"Writing fatal message","attr":{"message":"DBException::toString(): Location6493100: Time monotonicity violation: lookup time { chunkVersion: { e: …
```

PBM-1583: Exclude logical session docs from routing collections during restore

---

pbm/version/version.go
pbm/version/version_test.go

[![PBM-1597](https://badgen.net/badge/JIRA/PBM-1597/green)](https://jira.percona.com/browse/PBM-1597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
PBM currently emits a generic incompatibility message. We need clearer guidance:
If MongoDB is below the minimum supported version, instruct users to upgrade MongoDB.
If MongoDB is newer than supported (or has an unsupported minor version), instruct users to upgrade PBM.
Always list supported versions and the detected version.
Update PBMSupport() in pbm/version/version.go to:
Centralize supported MongoDB majors: []int{5, 6, 7, 8}.
For …

PBM-1597 - improve version check message

---

pbm/backup/storage.go
pbm/restore/physical.go
pbm/storage/azure/azure.go
pbm/storage/fs/fs.go
pbm/storage/fs/fs_test.go
pbm/storage/gcs/gcs.go
pbm/storage/gcs/gcs_test.go
pbm/storage/gcs/google_client.go
pbm/storage/s3/s3.go
pbm/storage/s3/s3_test.go
pbm/storage/split_merge_mw.go
pbm/storage/split_merge_mw_test.go
pbm/storage/storage.go
pbm/storage/storage_test_helpers.go
pbm/util/storage.go

[![PBM-1490](https://badgen.net/badge/JIRA/PBM-1490/green)](https://jira.percona.com/browse/PBM-1490) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This PR implements solution for handling backup files that exceed remote storage size limits by introducing a `split-merge` middleware. The middleware automatically splits large files into smaller parts during the backup procedure and merges them back during restore procedure. 
The file size threshold is set by default for each storage service, or it can be optionally set by configuration parameter:
| Storage        | Default Size | Config …

PBM-1490: Backup with files that have reached remote storage limits

---

pbm/storage/split_merge_mw.go
pbm/storage/split_merge_mw_test.go

[![PBM-1490](https://badgen.net/badge/JIRA/PBM-1490/green)](https://jira.percona.com/browse/PBM-1490) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
PR improves `storage.GetBasePart` function by removing unnecessary regex compilation and matching which makes the implementation simpler and more performant.
[PBM-1490]: https://perconadev.atlassian.net/browse/PBM-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PBM-1490: Improve storage.GetBasePart

---

cmd/pbm/restore.go
pbm/restore/physical.go
pbm/restore/storage.go
sdk/impl.go

[![PBM-1574](https://badgen.net/badge/JIRA/PBM-1574/green)](https://jira.percona.com/browse/PBM-1574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Physical restore includes a `cleaning up` phase at the end of the restore procedure (after it reaches final status: `Done`, `PartlyDone` or `Error` ). 
This PR fixes the issue when restore command is invoked with `--wait` option for the physical restore:
```
pbm restore --wait <backup-id>
```
and the `--wait` option doesn't include the cleaning up phase as part of the waiting.
PR expands the restore procedure to wait during the cleanup …

PBM-1574: PBM restore with -w doesn't wait till the end of restore

---

pbm/config/config.go
pbm/config/config_test.go
pbm/storage/azure/azure.go
pbm/storage/fs/fs.go
pbm/storage/gcs/gcs.go
pbm/storage/s3/s3.go

[![PBM-1490](https://badgen.net/badge/JIRA/PBM-1490/green)](https://jira.percona.com/browse/PBM-1490) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This is additional fix for #1183.
It fixes missing `IsSameStorage` check during performing incremental backup for FS.
[PBM-1490]: https://perconadev.atlassian.net/browse/PBM-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PBM-1490: Fix IsSameStorage check for incremental backup

---

packaging/debian/rules

It was mistakenly removed in https://github.com/percona/percona-backup-mongodb/pull/1160

PBM. Fix PBM deb package build
