percona/percona-backup-mongodb

cli/pbm-coordinator/main.go
grpc/client/client.go
grpc/server/clients.go
internal/cluster/cluster.go
internal/oplog/oplog_apply_test.go
internal/oplog/oplog_tail.go
internal/testutils/env.go
internal/testutils/grpc/daemon.go
tests/general_test.go

Fix misspell suggestions:
https://goreportcard.com/report/github.com/percona/percona-backup-mongodb#misspell

Fix mispellings

---

cli/pbmctl/main.go

Use gzip as default, similar to Percona-Lab/mongodb_consistent_backup

PBM-104: Use gzip as default for backup

---

Gopkg.lock
docker/pbmctl/Dockerfile

Add backup-restore.sh (and deps) to pbmctl Dockerfile temporarily to resolve CLOUD-99.
This image can become a simple alpine image + binary once restores are working.

Add backup-restore.sh (and deps) 

---

grpc/api/api.go
grpc/server/server.go

Also added error handling in several places.
Made changes for go-lint

PBM-123 Fixed logging

---

grpc/client/client.go
grpc/client/client_test.go

PBM-185 Fix agent crash if MongoDB connection is lost

PBM-185 Fix agent crash if MongoDB connection is lost

---

cli/pbm-agent/main.go
grpc/client/client.go

Fixes https://jira.percona.com/browse/PBM-247 and https://jira.percona.com/browse/PBM-210

[pbm-agent] change some options layout in the config

---

cli/pbm-agent/main.go

Fixes https://jira.percona.com/browse/PBM-249

[pbm-agent] remove login/pass checks to work with the no-auth-enabled mongo

---

grpc/client/client.go

... and re-register back again when mongo gets back
Fixes https://jira.percona.com/browse/PBM-239

PBM-239 Unregister the agent in case of mongo loss

---

grpc/server/server.go

Fixes https://jira.percona.com/browse/PBM-192

Release server status "locks" on errors

---

internal/oplog/oplog_apply.go
internal/oplog/oplog_apply_test.go

New filter to ignore system collections when re-applying the oplog

PBM-218 Filter for oplog apply

---

grpc/server/server.go
grpc/server/server_test.go
tests/general_test.go

PBM-259 Fixed find sources for restore

---

packaging/debian/rules
packaging/rpm/mongodb-backup.spec
packaging/scripts/mongodb-backup_builder.sh

Fix binaries output for "version" param.

Pbm 335 incomplete version information in binaries

---

go.sum
pbm/backup/backup.go
pbm/backup/dst.go
pbm/backup/oplog.go

In a simplicity sake and better error handling

Changed read/write layout 

---

pbm/backup/backup.go
pbm/backup/oplog.go

also add more error handling for the oplog tailing

PBM-361 - use logical clock for oplog tailing

---

cmd/pbm/main.go
pbm/restore/src.go
pbm/storage/s3/s3.go

Also has a few other fixes (see commit messages)

PBM-468 Fix invalid date format for backup delete command

---

docker/Dockerfile.k8s

https://cloud.cd.percona.com/job/pbm-docker-build/194/

K8SPSMDB-235 Fix build of docker image

---

doc/source/_templates/edit.html
doc/source/conf.py

modified conf.py
added _templates/edit.html file

PBM-548 Added the Edit on Github link to docs

---

doc/source/index.rst

PBM-549 Removed Contact us section

---

doc/source/architecture.rst

Reworked the intro paragraphs by listing architecture compoments and giving a brief overview of each

PBM-553 Updated PBM architecture

---

doc/source/.res/code-block/yaml/example-amazon-s3-storage.yaml
doc/source/.res/code-block/yaml/example-gcs-s3-storage.yaml
doc/source/.res/code-block/yaml/example-minio-s3-storage.yaml
doc/source/config.rst
doc/source/glossary.rst

Added S3 and filesystem config options
Added GCS config file example
Modified AWS and Minio examples to include prefix
Reordered and reformatted doc sections

PBM-531 Listed all config options in examples

---

cmd/pbm-speed-test/main.go

https://jira.percona.com/browse/PBM-560

PBM-560: align default compression for speed-test with pbm

---

doc/source/config.rst

Added UploadPartSize to the config options table

PBM-485 Documented UploadPartSize option

---

doc/source/running.rst

Added a subsection for restoring large backups
modified:   source/running.rst

PBM-559 Documented restore config options

---

doc/source/.res/code-block/yaml/example-amazon-s3-storage.yaml
doc/source/.res/replace.txt
doc/source/config.rst
doc/source/glossary.rst

Added server-side encryption options to the config options section
Extended config file example
Added a note about SSE support in PBM 1.3.2

PBM-426 Described SSE options

---

agent/agent.go
agent/pitr.go
agent/snapshot.go
cmd/pbm-speed-test/main.go
cmd/pbm/backup.go
cmd/pbm/logs.go
cmd/pbm/main.go
pbm/backup/backup.go
pbm/config.go
pbm/delete.go
pbm/log/log.go
pbm/node.go
pbm/pbm.go
pbm/pitr/pitr.go
pbm/restore/restore.go
pbm/rsync.go
pbm/storage/s3/s3.go

Added logs listing into pbm CLI
`pbm logs` options:
```
--tail=20                  Show last N entries
--node=NODE                Target node in format replset[/host:posrt]
--type=TYPE                Entry type <INFO>/<Warning>/<ERROR>
--event=EVENT              Event in format backup[/2020-10-06T11:45:14Z]
```
Requests & output examples:
```
$ pbm logs --tail=100 --node=rs1/localhost:37020 --event=backup
2020-10-15T20:42:07.000+0300 [INFO] backup/2020-10-15T17:41:50Z: backup started
2020-10-15T20:42:10.000+0300 [INFO] backup/2020-10-15T17:41:50Z: s3.uploadPartSize is set to 10485760 (~10Mb)
2020-10-15T20:42:10.000+0300 [ERROR] backup/2020-10-15T17:41:50Z: backup: mongodump: write data: upload to S3: RequestError: send request failed
caused by: Put …
```

PBM-345 Centralize logs

---

cmd/pbm/backup.go
cmd/pbm/logs.go
cmd/pbm/main.go
pbm/log/log.go
pbm/pbm.go

Defined severity also includes all more severe levels. E.g. [W]arning would also display [E]error & [F]atal levels.
Also added JSON output for logs
Examples:
```
$ pbm logs -t 100 -e backup -s W
2020-10-16T19:14:16.000+0300 E [rs2/localhost:28020] [backup/2020-10-16T16:13:55Z] backup: mongodump: write data: upload to S3: RequestError: send request failed
caused by: Post "http://127.0.0.1:9000/bkt/pbm/2020-10-16T16%3A13%3A55Z_rs2.dump.s2?uploads=": dial tcp 127.0.0.1:9000: connect: connection refused.
2020-10-16T19:14:16.000+0300 E [rs1/localhost:37019] [backup/2020-10-16T16:13:55Z] backup: mongodump: write data: upload to S3: RequestError: send request failed
caused by: Put "http://127.0.0.1:9000/bkt/pbm/2020-10-16T16%3A13%3A55Z_rs1.dump.s2": dial tcp 127.0.0.1:9000: connect: connection …
```

PBM-345 Rework logs layout

---

pbm/log/log.go

```
2020-10-27T17:34:56Z I [backup/2020-10-27T17:34:39Z] backup started
2020-10-27T17:34:59Z I [backup/2020-10-27T17:34:39Z] s3.uploadPartSize is set to 10485760 (~10Mb)
2020-10-27T17:35:10Z I [backup/2020-10-27T17:34:39Z] mongodump finished, waiting for the oplog
2020-10-27T17:35:12Z I [backup/2020-10-27T17:34:39Z] s3.uploadPartSize is set to 10485760 (~10Mb)
2020-10-27T17:35:14Z I [backup/2020-10-27T17:34:39Z] backup finished
```

PBM-345 feature: Logs: display time in CLI in UTC

---

doc/source/architecture.rst
doc/source/glossary.rst
doc/source/running.rst
doc/source/upgrading.rst

Reworded run pbm-agent example

PBM-600 Fixed incorrect rendering of a variable

---

agent/agent.go
cmd/pbm-agent/main.go
cmd/pbm/backup.go
cmd/pbm/main.go
cmd/pbm/status.go
pbm/pbm.go
pbm/pitr.go
pbm/restore/restore.go
pbm/rsync.go
pbm/storage/blackhole/blackhole.go
pbm/storage/fs/fs.go
pbm/storage/s3/s3.go
pbm/storage/storage.go

https://jira.percona.com/browse/PBM-435

PBM-435 pbm status command

---

cmd/pbm/backup.go
cmd/pbm/status.go

no cancelled, tunning, failed etc backups in `pbm list` - for that `pbm status`
Plus PBM-572: show the last write time of the backup
https://jira.percona.com/browse/PBM-603
https://jira.percona.com/browse/PBM-572

PBM-603: pbm list show only completed backups

---

cmd/pbm/status.go
e2e-tests/pkg/pbm/pbm_ctl.go
e2e-tests/pkg/tests/sharded/cluster.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
e2e-tests/run-consistency

...in case shard != RS name
And fix tests

PBM-435 fix: status of PITR ranges and cluster topology 

---

pbm/rsync.go

https://jira.percona.com/browse/PBM-612

PBM-612 fix: resync of PITR slices

---

doc/source/status.rst

PBM-624 Doc: Fixed incomplete description for the pbm status command

---

doc/source/architecture.rst

modified: source/architectire.rst

PBM-607 Added missing PBM Control collections to the list

---

doc/source/point-in-time-recovery.rst
doc/source/running.rst

modified:   source/point-in-time-recovery.rst
modified:   source/running.rst

PBM-622 Doc: Updated pbm list output in docs

---

doc/source/conf.py
doc/source/copyright.rst

modified:   source/conf.py
modified:   source/copyright.rst

PBM-633 Doc: updated year in copyright

---

pbm/backup/backup.go

Changes introduced in https://github.com/percona/percona-backup-mongodb/pull/396 broke error propagation during backup. Condition for marking the replset meta with an error was always unreachable since meta status wasn't reread from the DB but rather used the local "init" version. As the result, if one agent failed during the backup it would exit with an error but error state won't be propagated to the backup meta so other agents would be stuck in waiting of failed node to move further (as they hadn't observed the node actually failed).
This commit removes that condition for the replset' meta updates. 
After the introduction of OPID and operations log, there is no need in extra effort to deal with lagging nodes. PBM oplog solves that. (commit: …

Revert PBM-520: fix node' fails propagation during backup

---

pbm/pbm.go

Remove unused consts

---

doc/source/index.rst
doc/source/schedule-backup.rst

PBM-648 Doc: How to schedule backups using cron

---

README.md

Added overview, architecture, installation instructions, licensing
Updated contact ways

PBM-438 Doc: README updates

---

doc/source/index.rst

Hi Anastasia.
It seems some people hearing of the hot backup in PSMDB get confused and think PBM supports it too. I looked at the top page and thinkg the Feature list there is probably the best place in the whole documentation to point out that hot backup is not supported.
Whilst making the edit I got a little carried away and edited some other parts of the feature list too.
Would appreciate your opinion on these edit suggestions.

Mention that hot backups are not supported

---

CONTRIBUTING.md
doc/source/installation.rst

modified:   ../CONTRIBUTING.md
modified:   source/installation.rst

PBM-654 Doc: Add lbs for Kerberos authentication to install instructions

---

agent/agent.go
agent/snapshot.go
e2e-tests/run-new-cluster
pbm/agent_status.go
pbm/backup/backup.go
pbm/bcp_nodes_priority.go
pbm/bsontypes.go
pbm/config.go
pbm/pbm.go

Design doc: https://docs.google.com/document/d/1x8TK7OWSj9DlM_6fP7RXWtzxYS-CP3PHN4GT6m8X5DM
Config example:
```
backup:
priority:
"localhost:28019": 2.5
"localhost:37028": 2.5
"localhost:37029": 2.0
"localhost:37019": 0.1
```
https://jira.percona.com/browse/PBM-488

PBM-488: Method to influence which pbm-agent node will do backups

---

pbm/storage/fs/fs.go

Fixed pitr filesize always showing  zero on windows

Fixed pitr filesize always showing  zero on windows

---

doc/source/pbm-commands.rst

modified:   source/pbm-commands.rst

PBM-664 Added pbm list to commands page

---

CONTRIBUTING.md

Updated the testing section with the recommendation what tests to run depending on the development stage
modified:   ../CONTRIBUTING.md

PBM-666 Doc: Contributing guide update

---

agent/snapshot.go
pbm/backup/backup.go
pbm/bsontypes.go
pbm/pbm.go

https://jira.percona.com/browse/PBM-646

PBM-646: Stop the balancer during backup

---

doc/source/point-in-time-recovery.rst

modified: point-in-time-recobery.rst

PBM-671 Extended PIT restore section

---

doc/source/.res/code-block/yaml/example-azure-storage.yaml
doc/source/configuration-options.rst
doc/source/glossary.rst
doc/source/initial-setup.rst
doc/source/storage-configuration.rst

modified:   source/configuration-options.rst
modified:   source/initial-setup.rst
modified:   source/storage-configuration.rst

PBM-596 Doc: Azure storage support

---

doc/source/running.rst
doc/source/upgrading.rst

modified:   source/running.rst
modified:   source/upgrading.rst

PBM-659 Note about backup incompatibility with PBM 1.4.1 and 1.5.0

---

CONTRIBUTING.md
doc/source/architecture.rst
doc/source/configuration-options.rst
doc/source/running.rst

Added a subsection to Making a backup section in running.rst
Updated config file options page

PBM-488 Doc: pbm-agent weight for backups

---

doc/source/installation.rst
doc/source/running.rst

install from tarball
linked to DockerHub image.
Corrected directive syntax for running.rst
modified:   source/installation.rst

PBM-685 Described additional install options:

---

agent/pitr.go
cmd/pbm/status.go
e2e-tests/cmd/pbm-test/run.go
e2e-tests/pkg/pbm/mongo_pbm.go
e2e-tests/pkg/pbm/pbm_ctl.go
e2e-tests/pkg/tests/sharded/cluster.go
e2e-tests/pkg/tests/sharded/test_delete_backup.go
e2e-tests/pkg/tests/sharded/test_pitr_basic.go
pbm/pitr.go
pbm/pitr/pitr.go
pbm/pitr_test.go
pbm/storage/azure/azure.go
pbm/storage/fs/fs.go

related https://jira.percona.com/browse/PBM-617

PBM-688: CI tests for PBM-617

---

pbm/config.go
pbm/storage/fs/fs.go

https://jira.percona.com/browse/PBM-480

PBM-480: config fs.path is required

---

doc/source/configuration-options.rst
doc/source/schedule-backup.rst

modified:   source/configuration-options.rst
modified:   source/schedule-backup.rst

PBM-696 Fix Sphinx warnings

---

pbm/restore/restore.go

https://jira.percona.com/browse/PBM-703

PBM-703: exclude config.transactions from restore

---

pbm/storage/s3/s3.go

The last chunk during the PITR restore usually won't be read fully (high chances that the targeted time will be in the middle of the chunk) so in this case, the reader (oplog.Apply) will close the pipe once reaching the targeted time. And this is no case for logging the error.

PBM-705: don't write error when reader close the pipe

---

doc/source/pbm-commands.rst
doc/source/point-in-time-recovery.rst

modified:   source/pbm-commands.rst
modified:   source/point-in-time-recovery.rst

PBM-652 Described new way to delete backups and pitr chunks

---

doc/source/conf.py
doc/source/release-notes.rst
doc/source/release-notes/1.6.0.rst

modified:   source/conf.py
modified:   source/release-notes.rst
new file:   source/release-notes/1.6.0.rst

PBM-698 Release notes for 1.6.0

---

pbm/restore/oplog.go

`startIndexBuild` and `abortIndexBuild` should be ignored during oplog replay.
https://jira.percona.com/browse/PBM-702

PBM-702 fix: Unrecognized command during oplog replay

---

doc/source/pbm-commands.rst

modified:   source/pbm-commands.rst

PBM-711 Doc: Fixed table alignment from right to auto

---

doc/source/installation.rst

modified:   source/installation.rst

ENG-1051 Fix redirects to percona-release docs for PBM

---

pbm/storage/s3/s3.go

This PR adds s3 chain credentials support.
This will allow using ec2 instance profile, or tools like kiam, kube2iam or irsa.

feat: add s3 chain credentials support

---

doc/source/initial-setup.rst
doc/source/installation.rst
doc/source/pbm-commands.rst
doc/source/upgrading.rst

Fixed tex alignment in pbm version command
Fixed option syntax in initial setup doc

PBM-727 Replaced apt-get with apt in install and upgrade docs

---

doc/source/automate-s3-access.rst
doc/source/configuration-options.rst
doc/source/index.rst

a for authentication to S3
new file:   source/automate-s3-access.rst
modified:   source/configuration-options.rst
modified:   source/index.rst

PBM-740 Doc: Support for EC2 metadat

---

doc/source/conf.py
doc/source/release-notes.rst
doc/source/release-notes/1.6.1.rst

new file:source/release-notes/1.6.1.rst
modified:   source/conf.py
modified:   source/release-notes.rst

PBM-737 Release notes 1.6.1

---

doc/source/_static/custom.css
doc/source/_templates/material-theme/header.html
doc/source/_templates/material-theme/layout.html
doc/source/_templates/material-theme/relbar2.html
doc/source/_templates/material-theme/sidebar.html
doc/source/conf-netlify/conf.py

modified:   source/_static/custom.css
modified:   source/conf-netlify/conf.py
new directory: source/_templates/material-theme/

PBM-747 Layout changes for doc migration to netlify

---

doc/source/configuration-options.rst
pbm/storage/s3/s3.go

https://jira.percona.com/projects/PBM/issues/PBM-750

[PBM-750] Make max number of S3 upload parts configurable

---

doc/source/configuration-options.rst
pbm/storage/s3/s3.go

https://jira.percona.com/projects/PBM/issues/PBM-577

[PBM-577] Support choice of S3 storage class

---

pbm/storage/s3/s3.go

Add new config option `storage.s3.insecureSkipTLSVerify` that allows to skip TLS verification for S3-like storages.

[PBM-680] Skip TLS verification for object storage

---

docker/start-agent.sh

https://jira.percona.com/browse/K8SPSMDB-608

K8SPSMDB-608 - password of backup user is printed in backup-agent logs

---

pbm/storage/s3/s3.go

storage.s3.debugLog option enables S3 requests debug logging

[PBM-734] add storage.s3.debugLog option

---

cli/backup.go
cli/cli.go
cmd/pbm-speed-test/main.go
pbm/backup/backup.go
pbm/backup/dst.go
pbm/pbm.go
pbm/pitr/pitr.go
speedt/speedt.go

https://jira.percona.com/browse/PBM-756

[PBM-756] Support configurable compression level for backups

---

cli/cli.go
cmd/pbm-speed-test/main.go
doc/source/pbm-commands.rst
doc/source/running.rst
doc/source/troubleshooting.rst
pbm/backup/backup.go
pbm/backup/dst.go
pbm/pbm.go
pbm/pitr/pitr.go
pbm/restore/src.go

https://jira.percona.com/browse/PBM-764

[PBM-764] Support Zstandard compression format

---

pbm/config.go

https://jira.percona.com/browse/PBM-777

[PBM-777] Expand/fix config related API

---

pbm/pbm.go
pbm/pitr/pitr.go

https://jira.percona.com/browse/PBM-809

PBM-809: fix pitr files compression suffix

---

pbm/restore/physical.go

PITR should be turned off after the physical restore. Otherwise, if it was on during the backup, after the user runs the cluster again the slicing resumes in the state of the backup's time. Hence the system knows nothing about the recent restore and chunks made after the backup. So it would successfully start slicing and would overwrite chunks after the backup.

PBM-805: trun off pitr after the physical restore

---

pbm/restore/logical.go

Up until v1.7.0 the compression of pitr chunks was always S2.
But it was a mess in the code which lead to saving pitr chunk files
with the `.snappy` extension although it was S2 in fact. And during
the restore, decompression treated .snappy as S2 ¯\_(ツ)_/¯ It wasn’t
an issue since there was no choice. Now, Snappy produces `.snappy` files
and S2 - `.s2` which is ok. But this means the old chunks (made by previous
PBM versions) won’t be compatible - during the restore, PBM will treat such
files as Snappy (judging by its suffix) but in fact, they are s2 files
and restore will fail with snappy: corrupt input. So we try S2 in such a case.

PBM-809: Restore pitr chunks - try s2 if snappy failed

---

cli/cli.go

https://jira.percona.com/projects/PBM/issues/PBM-751

[PBM-751] Format timestamps according to RFC3339

---

packaging/debian/install
packaging/debian/rules
packaging/rpm/mongodb-backup.spec

PBM-828 add full config reference file to packages

---

packaging/conf/pbm-conf-reference.yml

modified:   pbm-conf-reference.yml

PBM-870 Added new config options to conf file reference

---

README.md

PBM-893 Fixed code syntax in Readme

---

go.mod
go.sum
vendor/golang.org/x/net/context/go17.go
vendor/golang.org/x/net/http/httpproxy/proxy.go
vendor/modules.txt

PBM-959: update golang.org/x/net mod

---

pbm/restore/physical.go

https://jira.percona.com/browse/PBM-957

PBM-957: phys restore: don't flush dbPath after local success

---

cli/config.go

```
$> cat "$CONFIG_PATH" | pbm config --file="-"
```

[PBM-877] read config file from stdin

---

pbm/storage/s3/s3.go

PBM-974: fix S3 copy of SSE encoded object

---

agent/agent.go
cli/cli.go
cli/delete.go
e2e-tests/pkg/pbm/mongo_pbm.go
pbm/delete.go
pbm/pbm.go
pbm/pitr.go

along with PBM-976 and PBM-908 changes as related

Revert "[PBM-850] ability to delete older backups 

---

pbm/restore/physical.go

Sometimes Mongo (WiredTiger) needs more time to start. ServerSelectionTimeout for connection ping should be increased. Not to wait to log stop restore due in case of the mongo fail we check mongo logs in-between tries and continue only if there are no errors.
https://jira.percona.com/browse/PBM-998

PBM-998: phys restore, wait for mongod to up during internal starts

---

pbm/restore/physical.go

The contents of the mongod log file is not a single JSON object but a series of unrelated JSON objects.
Decode multiple JSON values from the source one-by-one.

PBM-998: fix json decoding error

---

pbm/restore/physical.go

PBM-998: phys restore: wait for mongod shutdown

---

agent/snapshot.go

Apply upvote for all replica sets, not primary (config server) only

PBM-999: fix incr backups voting for all rs

---

pbm/oplog/restore.go

add more index building commands

PBM-1008: extend oplog commands for selective restore

---

Jenkinsfile
e2e-tests/docker/docker-compose-remapping.yaml
e2e-tests/docker/docker-compose-rs.yaml
e2e-tests/docker/docker-compose-single.yaml
e2e-tests/docker/docker-compose.yaml
e2e-tests/docker/pbm-agent/Dockerfile
e2e-tests/docker/scripts/start.sh
e2e-tests/functions

Changes mostly needed to be able to run PSMDB arm64 packages
Plus, add PSMDB v6.0 tests

Tests: use PSMDB mongo client for agent + add v6.0 

---

pbm/backup/physical.go

We don't need any previous incremental backup history when we start a base backup. So we can flush it to free up resources.

PBM-1033: flush incremental backup history

---

docker/Dockerfile

sync with Dockerfile.k8s
see https://github.com/percona/percona-backup-mongodb/pull/777

ubi8 base image

---

pbm/restore/physical.go

Extra shards on the target cluster will result in undefined behaviour after the physical restore as we in fact recreate the cluster, and don't just apply data on top of the existing one like with logical restore
For example:
shards in the backup:
- cfg
- rs1
- rs2
shards on the target cluster:
- cfg
- rs1
Restore will result in the error:
```
no data in the backup for the replica set rs2
```
https://jira.percona.com/browse/PBM-1052

PBM-1052: don't allow phys restore if cluster has extra shards

---

README.md

mention about non-library repo

note about non-public api

---

e2e-tests/docker/docker-compose.yaml
e2e-tests/docker/pbm-agent/Dockerfile
e2e-tests/functions
e2e-tests/pkg/pbm/mongod.go
e2e-tests/pkg/tests/sharded/test_selective.go

1) change backup name parsing to be suitable for mongo/mongosh
2) install tc for network cut test
3) drop collection if it's impossible to remove documents
4) fix for selective backup/restore tests

Fix tests for PBM

---

packaging/conf/pbm-conf-reference.yml

Added AWS token, mongod binary path, concurrent download options

PBM-1099 Updated pbm config reference

---

agent/snapshot.go
pbm/backup/backup.go
pbm/node.go
pbm/pbm.go
pbm/restore/logical.go
pbm/restore/physical.go
pbm/restore/selective.go
pbm/snapshot/restore.go

Do shard remapping for every restore in router config

[PBM-1118, PBM-1112, PBM-1113] support customised shard names

---

pbm/storage/s3/s3.go

https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.206/aws#Config.S3ForcePathStyle

[PBM-1133] add storage.s3.forcePathStyle (boolean)

---

pbm/pitr/pitr.go

Only full logical backup keeps complete (all ops) oplog range between the backup's first and last op timestamps.
Selective backup could contain needed ops in the oplog for consistency in selected namespaces only.
`$backupCursor`-based backups (physical, external, incremental) make consistent data snapshots - no oplog needed.
The code changes fetch oplog from MongoDB if the last backup does not have it.

[PBM-1185] fetch oplog from MongoDB if the last backup does not have it

---

cmd/pbm/backup.go

PR for https://perconadev.atlassian.net/browse/PBM-1257

PBM-1257: Fix panic during command `describe-backup` with collections

---

cmd/pbm-agent/backup.go

Fix for https://perconadev.atlassian.net/browse/PBM-1319
This fix allows Cluster Leader to accept backup nomination (e.g. in the case when Cluster Leader's node has highest priority).
Bug affects following topologies:
- Highest backup priority has Primary member of RS topology
- Highest backup priority has Primary of Config Server for Sharded Cluster topology

PBM-1319: Fix nomination-election process in case of Cluster Leader

---

cmd/pbm-agent/pitr.go

PR for https://perconadev.atlassian.net/browse/PBM-1326
When the backup is interrupted (due to some error), and its lock is not removed, PITR procedure is blocked.
This PR adds a stale lock check to unblock PITR in that situation.

Add stale lock check for PITR

---

pbm/oplog/restore.go

PR for https://perconadev.atlassian.net/browse/PBM-1296

PBM-1296: PBM fails on PITR restore when timeseries collection was created during oplog slicing

---

pbm/backup/backup.go
pbm/backup/logical.go
pbm/backup/physical.go

the leader only sets the status. no reason to wait for known condition

PBM-1229: skip waitForStatus on the backup leader

---

pbm/archive/backup.go

PBM-1366: continue after dropping a collection

---

cmd/pbm/backup.go
pbm/archive/backup.go
pbm/archive/conv.go
pbm/backup/backup.go
pbm/backup/logical.go
pbm/backup/types.go
pbm/restore/logical.go
pbm/restore/physical.go
pbm/snapshot/restore.go

PBM-1358: support selective backup and restore with configshard

---

cmd/pbm-agent/restore.go
cmd/pbm-agent/restore_test.go
cmd/pbm/main.go

* Fix proper reading of NumParallelCollections from configuration - it was never read due to the default value from cmd param
* Add unit tests for processing proper value for the configuration

PBM-1414 fix reading the NumParallelCollections configuration

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/reviewdog.yml

https://app.codecov.io/github/percona/percona-backup-mongodb/pull/1072/indirect-changes

PBM coverage report for functional tests

---

cmd/pbm-agent/main.go
pbm/log/discard.go
pbm/log/log.go
pbm/log/logger.go

PR for https://perconadev.atlassian.net/browse/PBM-1473
Removes the option to set LogPath.

PBM-1473 - Improve PBM behavior when the log.path option is modified in the configuration file

---

pbm/oplog/db_tc_test.go
pbm/oplog/restore_test.go

Fix for the flaky test within `go-test` pipeline (`oplog` package).

Fix flaky test in oplog package

---

cmd/pbm-agent/main.go
cmd/pbm/main.go

- remove Cobra's completion cmd
- add check and output same error as before the migration

PBM-1466 cobra fixes

---

pbm/config/config.go
pbm/storage/gcs/gcs.go

- add ClientEmail to config
- update missing checks for print
- add missing equal method

PBM-1484 gcp sdk fix

---

cmd/pbm/restore.go
pbm/archive/conv.go
pbm/backup/backup.go
pbm/backup/logical.go
pbm/restore/physical.go
pbm/storage/azure/azure.go
pbm/storage/blackhole/blackhole.go
pbm/storage/fs/fs.go
pbm/storage/gcs/gcs.go
pbm/storage/s3/s3.go
pbm/storage/storage.go
pbm/storage/storage_test_helpers.go
pbm/util/storage.go

PR refactors storage api to better support `functional options` pattern introduced in #1118.

PBM-1531: Refactor storage api to use options for file size

---

cmd/pbm/status.go

Additional column showing the backup status has been added. 
We have 3 possibilities:
1. success -  when StatusDone or errIncompatible
2. failed - when StatusCancelled or StatusError
3. ongoing - default / when backup in progress

PBM-1544 - Add new column showing the backup "Status" to pbm status output

---

.github/workflows/pr-badge.yml

Add pr-badge config to generate Jira task badges in the PR description.
https://pullrequestbadge.com/

Add pr-badge config

---

packaging/scripts/mongodb-backup_builder.sh

[![PKG-731](https://badgen.net/badge/JIRA/PKG-731/green)](https://jira.percona.com/browse/PKG-731) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[PKG-731]: https://perconadev.atlassian.net/browse/PKG-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PKG-731 pbm: add OL10 support

---

pbm/restore/logical_cfgsvr_full_test.go

[![PBM-1583](https://badgen.net/badge/JIRA/PBM-1583/green)](https://jira.percona.com/browse/PBM-1583) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Additional tests for #1172 .
[PBM-1583]: https://perconadev.atlassian.net/browse/PBM-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PBM-1583: Tests for routing collections restore logic
